#!/bin/bash
./.github/scripts/golangci-lint-gen-configs.sh
golangci-lint run -c .golangci.yml ./...
golangci-lint run -c examples/.golangci.yml ./examples/...
golangci-lint run -c tests/slo/.golangci.yml ./tests/slo/...
