// Code generated by gtrace. DO NOT EDIT.

package trace

import (
	"context"
	"fmt"
	"os"
	"runtime/debug"
)

// Compose returns a new Discovery which has functional fields composed
// both from t and x.
func (t Discovery) Compose(x Discovery) (ret Discovery) {
	{
		h1 := t.OnDiscover
		h2 := x.OnDiscover
		ret.OnDiscover = func(d DiscoveryDiscoverStartInfo) func(DiscoveryDiscoverDoneInfo) {
			defer func() {
				if e := recover(); e != nil {
					os.Stderr.WriteString(fmt.Sprintf("panic recovered:%v:\n%s", e, debug.Stack()))
				}
			}()
			var r, r1 func(DiscoveryDiscoverDoneInfo)
			if h1 != nil {
				r = h1(d)
			}
			if h2 != nil {
				r1 = h2(d)
			}
			return func(d DiscoveryDiscoverDoneInfo) {
				defer func() {
					if e := recover(); e != nil {
						os.Stderr.WriteString(fmt.Sprintf("panic recovered:%v:\n%s", e, debug.Stack()))
					}
				}()
				if r != nil {
					r(d)
				}
				if r1 != nil {
					r1(d)
				}
			}
		}
	}
	{
		h1 := t.OnWhoAmI
		h2 := x.OnWhoAmI
		ret.OnWhoAmI = func(d DiscoveryWhoAmIStartInfo) func(DiscoveryWhoAmIDoneInfo) {
			defer func() {
				if e := recover(); e != nil {
					os.Stderr.WriteString(fmt.Sprintf("panic recovered:%v:\n%s", e, debug.Stack()))
				}
			}()
			var r, r1 func(DiscoveryWhoAmIDoneInfo)
			if h1 != nil {
				r = h1(d)
			}
			if h2 != nil {
				r1 = h2(d)
			}
			return func(d DiscoveryWhoAmIDoneInfo) {
				defer func() {
					if e := recover(); e != nil {
						os.Stderr.WriteString(fmt.Sprintf("panic recovered:%v:\n%s", e, debug.Stack()))
					}
				}()
				if r != nil {
					r(d)
				}
				if r1 != nil {
					r1(d)
				}
			}
		}
	}
	return ret
}
func (t Discovery) onDiscover(d DiscoveryDiscoverStartInfo) func(DiscoveryDiscoverDoneInfo) {
	fn := t.OnDiscover
	if fn == nil {
		return func(DiscoveryDiscoverDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DiscoveryDiscoverDoneInfo) {
			return
		}
	}
	return res
}
func (t Discovery) onWhoAmI(d DiscoveryWhoAmIStartInfo) func(DiscoveryWhoAmIDoneInfo) {
	fn := t.OnWhoAmI
	if fn == nil {
		return func(DiscoveryWhoAmIDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DiscoveryWhoAmIDoneInfo) {
			return
		}
	}
	return res
}
func DiscoveryOnDiscover(t Discovery, c *context.Context, address string, database string) func(location string, endpoints []EndpointInfo, _ error) {
	var p DiscoveryDiscoverStartInfo
	p.Context = c
	p.Address = address
	p.Database = database
	res := t.onDiscover(p)
	return func(location string, endpoints []EndpointInfo, e error) {
		var p DiscoveryDiscoverDoneInfo
		p.Location = location
		p.Endpoints = endpoints
		p.Error = e
		res(p)
	}
}
func DiscoveryOnWhoAmI(t Discovery, c *context.Context) func(user string, groups []string, _ error) {
	var p DiscoveryWhoAmIStartInfo
	p.Context = c
	res := t.onWhoAmI(p)
	return func(user string, groups []string, e error) {
		var p DiscoveryWhoAmIDoneInfo
		p.User = user
		p.Groups = groups
		p.Error = e
		res(p)
	}
}
