// Code generated by gtrace. DO NOT EDIT.

package trace

import (
	"context"
)

// Compose returns a new Driver which has functional fields composed
// both from t and x.
func (t Driver) Compose(x Driver) (ret Driver) {
	switch {
	case t.OnInit == nil:
		ret.OnInit = x.OnInit
	case x.OnInit == nil:
		ret.OnInit = t.OnInit
	default:
		h1 := t.OnInit
		h2 := x.OnInit
		ret.OnInit = func(d DriverInitStartInfo) func(DriverInitDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverInitDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnClose == nil:
		ret.OnClose = x.OnClose
	case x.OnClose == nil:
		ret.OnClose = t.OnClose
	default:
		h1 := t.OnClose
		h2 := x.OnClose
		ret.OnClose = func(d DriverCloseStartInfo) func(DriverCloseDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverCloseDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnNetRead == nil:
		ret.OnNetRead = x.OnNetRead
	case x.OnNetRead == nil:
		ret.OnNetRead = t.OnNetRead
	default:
		h1 := t.OnNetRead
		h2 := x.OnNetRead
		ret.OnNetRead = func(d DriverNetReadStartInfo) func(DriverNetReadDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverNetReadDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnNetWrite == nil:
		ret.OnNetWrite = x.OnNetWrite
	case x.OnNetWrite == nil:
		ret.OnNetWrite = t.OnNetWrite
	default:
		h1 := t.OnNetWrite
		h2 := x.OnNetWrite
		ret.OnNetWrite = func(d DriverNetWriteStartInfo) func(DriverNetWriteDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverNetWriteDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnNetDial == nil:
		ret.OnNetDial = x.OnNetDial
	case x.OnNetDial == nil:
		ret.OnNetDial = t.OnNetDial
	default:
		h1 := t.OnNetDial
		h2 := x.OnNetDial
		ret.OnNetDial = func(d DriverNetDialStartInfo) func(DriverNetDialDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverNetDialDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnNetClose == nil:
		ret.OnNetClose = x.OnNetClose
	case x.OnNetClose == nil:
		ret.OnNetClose = t.OnNetClose
	default:
		h1 := t.OnNetClose
		h2 := x.OnNetClose
		ret.OnNetClose = func(d DriverNetCloseStartInfo) func(DriverNetCloseDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverNetCloseDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnResolve == nil:
		ret.OnResolve = x.OnResolve
	case x.OnResolve == nil:
		ret.OnResolve = t.OnResolve
	default:
		h1 := t.OnResolve
		h2 := x.OnResolve
		ret.OnResolve = func(d DriverResolveStartInfo) func(DriverResolveDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverResolveDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnConnStateChange == nil:
		ret.OnConnStateChange = x.OnConnStateChange
	case x.OnConnStateChange == nil:
		ret.OnConnStateChange = t.OnConnStateChange
	default:
		h1 := t.OnConnStateChange
		h2 := x.OnConnStateChange
		ret.OnConnStateChange = func(d DriverConnStateChangeStartInfo) func(DriverConnStateChangeDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverConnStateChangeDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnConnInvoke == nil:
		ret.OnConnInvoke = x.OnConnInvoke
	case x.OnConnInvoke == nil:
		ret.OnConnInvoke = t.OnConnInvoke
	default:
		h1 := t.OnConnInvoke
		h2 := x.OnConnInvoke
		ret.OnConnInvoke = func(d DriverConnInvokeStartInfo) func(DriverConnInvokeDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverConnInvokeDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnConnNewStream == nil:
		ret.OnConnNewStream = x.OnConnNewStream
	case x.OnConnNewStream == nil:
		ret.OnConnNewStream = t.OnConnNewStream
	default:
		h1 := t.OnConnNewStream
		h2 := x.OnConnNewStream
		ret.OnConnNewStream = func(d DriverConnNewStreamStartInfo) func(DriverConnNewStreamRecvInfo) func(DriverConnNewStreamDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverConnNewStreamRecvInfo) func(DriverConnNewStreamDoneInfo) {
					r11 := r1(d)
					r21 := r2(d)
					switch {
					case r11 == nil:
						return r21
					case r21 == nil:
						return r11
					default:
						return func(d DriverConnNewStreamDoneInfo) {
							r11(d)
							r21(d)
						}
					}
				}
			}
		}
	}
	switch {
	case t.OnConnTake == nil:
		ret.OnConnTake = x.OnConnTake
	case x.OnConnTake == nil:
		ret.OnConnTake = t.OnConnTake
	default:
		h1 := t.OnConnTake
		h2 := x.OnConnTake
		ret.OnConnTake = func(d DriverConnTakeStartInfo) func(DriverConnTakeDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverConnTakeDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnConnUsagesChange == nil:
		ret.OnConnUsagesChange = x.OnConnUsagesChange
	case x.OnConnUsagesChange == nil:
		ret.OnConnUsagesChange = t.OnConnUsagesChange
	default:
		h1 := t.OnConnUsagesChange
		h2 := x.OnConnUsagesChange
		ret.OnConnUsagesChange = func(d DriverConnUsagesChangeInfo) {
			h1(d)
			h2(d)
		}
	}
	switch {
	case t.OnConnStreamUsagesChange == nil:
		ret.OnConnStreamUsagesChange = x.OnConnStreamUsagesChange
	case x.OnConnStreamUsagesChange == nil:
		ret.OnConnStreamUsagesChange = t.OnConnStreamUsagesChange
	default:
		h1 := t.OnConnStreamUsagesChange
		h2 := x.OnConnStreamUsagesChange
		ret.OnConnStreamUsagesChange = func(d DriverConnStreamUsagesChangeInfo) {
			h1(d)
			h2(d)
		}
	}
	switch {
	case t.OnConnPark == nil:
		ret.OnConnPark = x.OnConnPark
	case x.OnConnPark == nil:
		ret.OnConnPark = t.OnConnPark
	default:
		h1 := t.OnConnPark
		h2 := x.OnConnPark
		ret.OnConnPark = func(d DriverConnParkStartInfo) func(DriverConnParkDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverConnParkDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnConnClose == nil:
		ret.OnConnClose = x.OnConnClose
	case x.OnConnClose == nil:
		ret.OnConnClose = t.OnConnClose
	default:
		h1 := t.OnConnClose
		h2 := x.OnConnClose
		ret.OnConnClose = func(d DriverConnCloseStartInfo) func(DriverConnCloseDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverConnCloseDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnConnRelease == nil:
		ret.OnConnRelease = x.OnConnRelease
	case x.OnConnRelease == nil:
		ret.OnConnRelease = t.OnConnRelease
	default:
		h1 := t.OnConnRelease
		h2 := x.OnConnRelease
		ret.OnConnRelease = func(d DriverConnReleaseStartInfo) func(DriverConnReleaseDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverConnReleaseDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnClusterInit == nil:
		ret.OnClusterInit = x.OnClusterInit
	case x.OnClusterInit == nil:
		ret.OnClusterInit = t.OnClusterInit
	default:
		h1 := t.OnClusterInit
		h2 := x.OnClusterInit
		ret.OnClusterInit = func(d DriverClusterInitStartInfo) func(DriverClusterInitDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverClusterInitDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnClusterClose == nil:
		ret.OnClusterClose = x.OnClusterClose
	case x.OnClusterClose == nil:
		ret.OnClusterClose = t.OnClusterClose
	default:
		h1 := t.OnClusterClose
		h2 := x.OnClusterClose
		ret.OnClusterClose = func(d DriverClusterCloseStartInfo) func(DriverClusterCloseDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverClusterCloseDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnClusterGet == nil:
		ret.OnClusterGet = x.OnClusterGet
	case x.OnClusterGet == nil:
		ret.OnClusterGet = t.OnClusterGet
	default:
		h1 := t.OnClusterGet
		h2 := x.OnClusterGet
		ret.OnClusterGet = func(d DriverClusterGetStartInfo) func(DriverClusterGetDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverClusterGetDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnClusterInsert == nil:
		ret.OnClusterInsert = x.OnClusterInsert
	case x.OnClusterInsert == nil:
		ret.OnClusterInsert = t.OnClusterInsert
	default:
		h1 := t.OnClusterInsert
		h2 := x.OnClusterInsert
		ret.OnClusterInsert = func(d DriverClusterInsertStartInfo) func(DriverClusterInsertDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverClusterInsertDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnClusterUpdate == nil:
		ret.OnClusterUpdate = x.OnClusterUpdate
	case x.OnClusterUpdate == nil:
		ret.OnClusterUpdate = t.OnClusterUpdate
	default:
		h1 := t.OnClusterUpdate
		h2 := x.OnClusterUpdate
		ret.OnClusterUpdate = func(d DriverClusterUpdateStartInfo) func(DriverClusterUpdateDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverClusterUpdateDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnClusterRemove == nil:
		ret.OnClusterRemove = x.OnClusterRemove
	case x.OnClusterRemove == nil:
		ret.OnClusterRemove = t.OnClusterRemove
	default:
		h1 := t.OnClusterRemove
		h2 := x.OnClusterRemove
		ret.OnClusterRemove = func(d DriverClusterRemoveStartInfo) func(DriverClusterRemoveDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverClusterRemoveDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnPessimizeNode == nil:
		ret.OnPessimizeNode = x.OnPessimizeNode
	case x.OnPessimizeNode == nil:
		ret.OnPessimizeNode = t.OnPessimizeNode
	default:
		h1 := t.OnPessimizeNode
		h2 := x.OnPessimizeNode
		ret.OnPessimizeNode = func(d DriverPessimizeNodeStartInfo) func(DriverPessimizeNodeDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverPessimizeNodeDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnRepeaterWakeUp == nil:
		ret.OnRepeaterWakeUp = x.OnRepeaterWakeUp
	case x.OnRepeaterWakeUp == nil:
		ret.OnRepeaterWakeUp = t.OnRepeaterWakeUp
	default:
		h1 := t.OnRepeaterWakeUp
		h2 := x.OnRepeaterWakeUp
		ret.OnRepeaterWakeUp = func(d DriverRepeaterTickStartInfo) func(DriverRepeaterTickDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverRepeaterTickDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	switch {
	case t.OnGetCredentials == nil:
		ret.OnGetCredentials = x.OnGetCredentials
	case x.OnGetCredentials == nil:
		ret.OnGetCredentials = t.OnGetCredentials
	default:
		h1 := t.OnGetCredentials
		h2 := x.OnGetCredentials
		ret.OnGetCredentials = func(d DriverGetCredentialsStartInfo) func(DriverGetCredentialsDoneInfo) {
			r1 := h1(d)
			r2 := h2(d)
			switch {
			case r1 == nil:
				return r2
			case r2 == nil:
				return r1
			default:
				return func(d DriverGetCredentialsDoneInfo) {
					r1(d)
					r2(d)
				}
			}
		}
	}
	return ret
}
func (t Driver) onInit(d DriverInitStartInfo) func(DriverInitDoneInfo) {
	fn := t.OnInit
	if fn == nil {
		return func(DriverInitDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverInitDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onClose(d DriverCloseStartInfo) func(DriverCloseDoneInfo) {
	fn := t.OnClose
	if fn == nil {
		return func(DriverCloseDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverCloseDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onNetRead(d DriverNetReadStartInfo) func(DriverNetReadDoneInfo) {
	fn := t.OnNetRead
	if fn == nil {
		return func(DriverNetReadDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverNetReadDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onNetWrite(d DriverNetWriteStartInfo) func(DriverNetWriteDoneInfo) {
	fn := t.OnNetWrite
	if fn == nil {
		return func(DriverNetWriteDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverNetWriteDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onNetDial(d DriverNetDialStartInfo) func(DriverNetDialDoneInfo) {
	fn := t.OnNetDial
	if fn == nil {
		return func(DriverNetDialDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverNetDialDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onNetClose(d DriverNetCloseStartInfo) func(DriverNetCloseDoneInfo) {
	fn := t.OnNetClose
	if fn == nil {
		return func(DriverNetCloseDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverNetCloseDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onResolve(d DriverResolveStartInfo) func(DriverResolveDoneInfo) {
	fn := t.OnResolve
	if fn == nil {
		return func(DriverResolveDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverResolveDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onConnStateChange(d DriverConnStateChangeStartInfo) func(DriverConnStateChangeDoneInfo) {
	fn := t.OnConnStateChange
	if fn == nil {
		return func(DriverConnStateChangeDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverConnStateChangeDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onConnInvoke(d DriverConnInvokeStartInfo) func(DriverConnInvokeDoneInfo) {
	fn := t.OnConnInvoke
	if fn == nil {
		return func(DriverConnInvokeDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverConnInvokeDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onConnNewStream(d DriverConnNewStreamStartInfo) func(DriverConnNewStreamRecvInfo) func(DriverConnNewStreamDoneInfo) {
	fn := t.OnConnNewStream
	if fn == nil {
		return func(DriverConnNewStreamRecvInfo) func(DriverConnNewStreamDoneInfo) {
			return func(DriverConnNewStreamDoneInfo) {
				return
			}
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverConnNewStreamRecvInfo) func(DriverConnNewStreamDoneInfo) {
			return func(DriverConnNewStreamDoneInfo) {
				return
			}
		}
	}
	return func(d DriverConnNewStreamRecvInfo) func(DriverConnNewStreamDoneInfo) {
		res := res(d)
		if res == nil {
			return func(DriverConnNewStreamDoneInfo) {
				return
			}
		}
		return res
	}
}
func (t Driver) onConnTake(d DriverConnTakeStartInfo) func(DriverConnTakeDoneInfo) {
	fn := t.OnConnTake
	if fn == nil {
		return func(DriverConnTakeDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverConnTakeDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onConnUsagesChange(d DriverConnUsagesChangeInfo) {
	fn := t.OnConnUsagesChange
	if fn == nil {
		return
	}
	fn(d)
}
func (t Driver) onConnStreamUsagesChange(d DriverConnStreamUsagesChangeInfo) {
	fn := t.OnConnStreamUsagesChange
	if fn == nil {
		return
	}
	fn(d)
}
func (t Driver) onConnPark(d DriverConnParkStartInfo) func(DriverConnParkDoneInfo) {
	fn := t.OnConnPark
	if fn == nil {
		return func(DriverConnParkDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverConnParkDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onConnClose(d DriverConnCloseStartInfo) func(DriverConnCloseDoneInfo) {
	fn := t.OnConnClose
	if fn == nil {
		return func(DriverConnCloseDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverConnCloseDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onConnRelease(d DriverConnReleaseStartInfo) func(DriverConnReleaseDoneInfo) {
	fn := t.OnConnRelease
	if fn == nil {
		return func(DriverConnReleaseDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverConnReleaseDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onClusterInit(d DriverClusterInitStartInfo) func(DriverClusterInitDoneInfo) {
	fn := t.OnClusterInit
	if fn == nil {
		return func(DriverClusterInitDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverClusterInitDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onClusterClose(d DriverClusterCloseStartInfo) func(DriverClusterCloseDoneInfo) {
	fn := t.OnClusterClose
	if fn == nil {
		return func(DriverClusterCloseDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverClusterCloseDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onClusterGet(d DriverClusterGetStartInfo) func(DriverClusterGetDoneInfo) {
	fn := t.OnClusterGet
	if fn == nil {
		return func(DriverClusterGetDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverClusterGetDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onClusterInsert(d DriverClusterInsertStartInfo) func(DriverClusterInsertDoneInfo) {
	fn := t.OnClusterInsert
	if fn == nil {
		return func(DriverClusterInsertDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverClusterInsertDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onClusterUpdate(d DriverClusterUpdateStartInfo) func(DriverClusterUpdateDoneInfo) {
	fn := t.OnClusterUpdate
	if fn == nil {
		return func(DriverClusterUpdateDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverClusterUpdateDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onClusterRemove(d DriverClusterRemoveStartInfo) func(DriverClusterRemoveDoneInfo) {
	fn := t.OnClusterRemove
	if fn == nil {
		return func(DriverClusterRemoveDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverClusterRemoveDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onPessimizeNode(d DriverPessimizeNodeStartInfo) func(DriverPessimizeNodeDoneInfo) {
	fn := t.OnPessimizeNode
	if fn == nil {
		return func(DriverPessimizeNodeDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverPessimizeNodeDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onRepeaterWakeUp(d DriverRepeaterTickStartInfo) func(DriverRepeaterTickDoneInfo) {
	fn := t.OnRepeaterWakeUp
	if fn == nil {
		return func(DriverRepeaterTickDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverRepeaterTickDoneInfo) {
			return
		}
	}
	return res
}
func (t Driver) onGetCredentials(d DriverGetCredentialsStartInfo) func(DriverGetCredentialsDoneInfo) {
	fn := t.OnGetCredentials
	if fn == nil {
		return func(DriverGetCredentialsDoneInfo) {
			return
		}
	}
	res := fn(d)
	if res == nil {
		return func(DriverGetCredentialsDoneInfo) {
			return
		}
	}
	return res
}
func DriverOnInit(t Driver, c *context.Context, endpoint string, database string, secure bool) func(error) {
	var p DriverInitStartInfo
	p.Context = c
	p.Endpoint = endpoint
	p.Database = database
	p.Secure = secure
	res := t.onInit(p)
	return func(e error) {
		var p DriverInitDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnClose(t Driver, c *context.Context) func(error) {
	var p DriverCloseStartInfo
	p.Context = c
	res := t.onClose(p)
	return func(e error) {
		var p DriverCloseDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnNetRead(t Driver, address string, buffer int) func(received int, _ error) {
	var p DriverNetReadStartInfo
	p.Address = address
	p.Buffer = buffer
	res := t.onNetRead(p)
	return func(received int, e error) {
		var p DriverNetReadDoneInfo
		p.Received = received
		p.Error = e
		res(p)
	}
}
func DriverOnNetWrite(t Driver, address string, bytes int) func(sent int, _ error) {
	var p DriverNetWriteStartInfo
	p.Address = address
	p.Bytes = bytes
	res := t.onNetWrite(p)
	return func(sent int, e error) {
		var p DriverNetWriteDoneInfo
		p.Sent = sent
		p.Error = e
		res(p)
	}
}
func DriverOnNetDial(t Driver, c *context.Context, address string) func(error) {
	var p DriverNetDialStartInfo
	p.Context = c
	p.Address = address
	res := t.onNetDial(p)
	return func(e error) {
		var p DriverNetDialDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnNetClose(t Driver, address string) func(error) {
	var p DriverNetCloseStartInfo
	p.Address = address
	res := t.onNetClose(p)
	return func(e error) {
		var p DriverNetCloseDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnResolve(t Driver, target string, resolved []string) func(error) {
	var p DriverResolveStartInfo
	p.Target = target
	p.Resolved = resolved
	res := t.onResolve(p)
	return func(e error) {
		var p DriverResolveDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnConnStateChange(t Driver, endpoint EndpointInfo, state ConnState) func(state ConnState) {
	var p DriverConnStateChangeStartInfo
	p.Endpoint = endpoint
	p.State = state
	res := t.onConnStateChange(p)
	return func(state ConnState) {
		var p DriverConnStateChangeDoneInfo
		p.State = state
		res(p)
	}
}
func DriverOnConnInvoke(t Driver, c *context.Context, endpoint EndpointInfo, m Method) func(_ error, issues []Issue, opID string, state ConnState) {
	var p DriverConnInvokeStartInfo
	p.Context = c
	p.Endpoint = endpoint
	p.Method = m
	res := t.onConnInvoke(p)
	return func(e error, issues []Issue, opID string, state ConnState) {
		var p DriverConnInvokeDoneInfo
		p.Error = e
		p.Issues = issues
		p.OpID = opID
		p.State = state
		res(p)
	}
}
func DriverOnConnNewStream(t Driver, c *context.Context, endpoint EndpointInfo, m Method) func(error) func(state ConnState, _ error) {
	var p DriverConnNewStreamStartInfo
	p.Context = c
	p.Endpoint = endpoint
	p.Method = m
	res := t.onConnNewStream(p)
	return func(e error) func(ConnState, error) {
		var p DriverConnNewStreamRecvInfo
		p.Error = e
		res := res(p)
		return func(state ConnState, e error) {
			var p DriverConnNewStreamDoneInfo
			p.State = state
			p.Error = e
			res(p)
		}
	}
}
func DriverOnConnTake(t Driver, c *context.Context, endpoint EndpointInfo) func(error) {
	var p DriverConnTakeStartInfo
	p.Context = c
	p.Endpoint = endpoint
	res := t.onConnTake(p)
	return func(e error) {
		var p DriverConnTakeDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnConnUsagesChange(t Driver, endpoint EndpointInfo, usages int) {
	var p DriverConnUsagesChangeInfo
	p.Endpoint = endpoint
	p.Usages = usages
	t.onConnUsagesChange(p)
}
func DriverOnConnStreamUsagesChange(t Driver, endpoint EndpointInfo, usages int) {
	var p DriverConnStreamUsagesChangeInfo
	p.Endpoint = endpoint
	p.Usages = usages
	t.onConnStreamUsagesChange(p)
}
func DriverOnConnPark(t Driver, c *context.Context, endpoint EndpointInfo) func(error) {
	var p DriverConnParkStartInfo
	p.Context = c
	p.Endpoint = endpoint
	res := t.onConnPark(p)
	return func(e error) {
		var p DriverConnParkDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnConnClose(t Driver, c *context.Context, endpoint EndpointInfo) func(error) {
	var p DriverConnCloseStartInfo
	p.Context = c
	p.Endpoint = endpoint
	res := t.onConnClose(p)
	return func(e error) {
		var p DriverConnCloseDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnConnRelease(t Driver, c *context.Context, endpoint EndpointInfo) func(error) {
	var p DriverConnReleaseStartInfo
	p.Context = c
	p.Endpoint = endpoint
	res := t.onConnRelease(p)
	return func(e error) {
		var p DriverConnReleaseDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnClusterInit(t Driver, c *context.Context) func(error) {
	var p DriverClusterInitStartInfo
	p.Context = c
	res := t.onClusterInit(p)
	return func(e error) {
		var p DriverClusterInitDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnClusterClose(t Driver, c *context.Context) func(error) {
	var p DriverClusterCloseStartInfo
	p.Context = c
	res := t.onClusterClose(p)
	return func(e error) {
		var p DriverClusterCloseDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnClusterGet(t Driver, c *context.Context) func(endpoint EndpointInfo, _ error) {
	var p DriverClusterGetStartInfo
	p.Context = c
	res := t.onClusterGet(p)
	return func(endpoint EndpointInfo, e error) {
		var p DriverClusterGetDoneInfo
		p.Endpoint = endpoint
		p.Error = e
		res(p)
	}
}
func DriverOnClusterInsert(t Driver, c *context.Context, endpoint EndpointInfo) func(inserted bool, state ConnState) {
	var p DriverClusterInsertStartInfo
	p.Context = c
	p.Endpoint = endpoint
	res := t.onClusterInsert(p)
	return func(inserted bool, state ConnState) {
		var p DriverClusterInsertDoneInfo
		p.Inserted = inserted
		p.State = state
		res(p)
	}
}
func DriverOnClusterUpdate(t Driver, c *context.Context, endpoint EndpointInfo) func(state ConnState) {
	var p DriverClusterUpdateStartInfo
	p.Context = c
	p.Endpoint = endpoint
	res := t.onClusterUpdate(p)
	return func(state ConnState) {
		var p DriverClusterUpdateDoneInfo
		p.State = state
		res(p)
	}
}
func DriverOnClusterRemove(t Driver, c *context.Context, endpoint EndpointInfo) func(state ConnState, removed bool) {
	var p DriverClusterRemoveStartInfo
	p.Context = c
	p.Endpoint = endpoint
	res := t.onClusterRemove(p)
	return func(state ConnState, removed bool) {
		var p DriverClusterRemoveDoneInfo
		p.State = state
		p.Removed = removed
		res(p)
	}
}
func DriverOnPessimizeNode(t Driver, c *context.Context, endpoint EndpointInfo, state ConnState, cause error) func(state ConnState) {
	var p DriverPessimizeNodeStartInfo
	p.Context = c
	p.Endpoint = endpoint
	p.State = state
	p.Cause = cause
	res := t.onPessimizeNode(p)
	return func(state ConnState) {
		var p DriverPessimizeNodeDoneInfo
		p.State = state
		res(p)
	}
}
func DriverOnRepeaterWakeUp(t Driver, c *context.Context, name string, event string) func(error) {
	var p DriverRepeaterTickStartInfo
	p.Context = c
	p.Name = name
	p.Event = event
	res := t.onRepeaterWakeUp(p)
	return func(e error) {
		var p DriverRepeaterTickDoneInfo
		p.Error = e
		res(p)
	}
}
func DriverOnGetCredentials(t Driver, c *context.Context) func(token string, _ error) {
	var p DriverGetCredentialsStartInfo
	p.Context = c
	res := t.onGetCredentials(p)
	return func(token string, e error) {
		var p DriverGetCredentialsDoneInfo
		p.Token = token
		p.Error = e
		res(p)
	}
}
