// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ydb_issue_message.proto

package Ydb_Issue

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// IssueMessage is a transport format for yql/public/issue library
type IssueMessage struct {
	Position    *IssueMessage_Position `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	Message     *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	EndPosition *IssueMessage_Position `protobuf:"bytes,3,opt,name=end_position,json=endPosition" json:"end_position,omitempty"`
	IssueCode   *uint32                `protobuf:"varint,4,opt,name=issue_code,json=issueCode" json:"issue_code,omitempty"`
	// Severity values from yql/public/issue/protos/issue_severity.proto
	// FATAL = 0;
	// ERROR = 1;
	// WARNING = 2;
	// INFO = 3;
	Severity             *uint32         `protobuf:"varint,5,opt,name=severity" json:"severity,omitempty"`
	Issues               []*IssueMessage `protobuf:"bytes,6,rep,name=issues" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IssueMessage) Reset()         { *m = IssueMessage{} }
func (m *IssueMessage) String() string { return proto.CompactTextString(m) }
func (*IssueMessage) ProtoMessage()    {}
func (*IssueMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b472e41df8bb0e5, []int{0}
}

func (m *IssueMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueMessage.Unmarshal(m, b)
}
func (m *IssueMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueMessage.Marshal(b, m, deterministic)
}
func (m *IssueMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueMessage.Merge(m, src)
}
func (m *IssueMessage) XXX_Size() int {
	return xxx_messageInfo_IssueMessage.Size(m)
}
func (m *IssueMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IssueMessage proto.InternalMessageInfo

func (m *IssueMessage) GetPosition() *IssueMessage_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *IssueMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *IssueMessage) GetEndPosition() *IssueMessage_Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *IssueMessage) GetIssueCode() uint32 {
	if m != nil && m.IssueCode != nil {
		return *m.IssueCode
	}
	return 0
}

func (m *IssueMessage) GetSeverity() uint32 {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return 0
}

func (m *IssueMessage) GetIssues() []*IssueMessage {
	if m != nil {
		return m.Issues
	}
	return nil
}

type IssueMessage_Position struct {
	Row                  *uint32  `protobuf:"varint,1,opt,name=row" json:"row,omitempty"`
	Column               *uint32  `protobuf:"varint,2,opt,name=column" json:"column,omitempty"`
	File                 *string  `protobuf:"bytes,3,opt,name=file" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueMessage_Position) Reset()         { *m = IssueMessage_Position{} }
func (m *IssueMessage_Position) String() string { return proto.CompactTextString(m) }
func (*IssueMessage_Position) ProtoMessage()    {}
func (*IssueMessage_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b472e41df8bb0e5, []int{0, 0}
}

func (m *IssueMessage_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueMessage_Position.Unmarshal(m, b)
}
func (m *IssueMessage_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueMessage_Position.Marshal(b, m, deterministic)
}
func (m *IssueMessage_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueMessage_Position.Merge(m, src)
}
func (m *IssueMessage_Position) XXX_Size() int {
	return xxx_messageInfo_IssueMessage_Position.Size(m)
}
func (m *IssueMessage_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueMessage_Position.DiscardUnknown(m)
}

var xxx_messageInfo_IssueMessage_Position proto.InternalMessageInfo

func (m *IssueMessage_Position) GetRow() uint32 {
	if m != nil && m.Row != nil {
		return *m.Row
	}
	return 0
}

func (m *IssueMessage_Position) GetColumn() uint32 {
	if m != nil && m.Column != nil {
		return *m.Column
	}
	return 0
}

func (m *IssueMessage_Position) GetFile() string {
	if m != nil && m.File != nil {
		return *m.File
	}
	return ""
}

func init() {
	proto.RegisterType((*IssueMessage)(nil), "Ydb.Issue.IssueMessage")
	proto.RegisterType((*IssueMessage_Position)(nil), "Ydb.Issue.IssueMessage.Position")
}

func init() { proto.RegisterFile("ydb_issue_message.proto", fileDescriptor_0b472e41df8bb0e5) }

var fileDescriptor_0b472e41df8bb0e5 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0x3a, 0x6b, 0xfb, 0xba, 0xa2, 0xbc, 0x83, 0x0b, 0x03, 0x21, 0x78, 0xea, 0x29,
	0xc2, 0xce, 0x9e, 0xdc, 0x45, 0x0f, 0x82, 0xe4, 0xe6, 0xa9, 0xac, 0xcb, 0x53, 0x02, 0x5b, 0x32,
	0x9a, 0x56, 0xed, 0x9f, 0xeb, 0x7f, 0x22, 0xcb, 0xb2, 0xe0, 0x45, 0xd8, 0xed, 0xfb, 0xf2, 0x7e,
	0x79, 0x1f, 0xdf, 0x83, 0xf9, 0xa8, 0xda, 0x46, 0x3b, 0x37, 0x50, 0xb3, 0x23, 0xe7, 0xd6, 0x1f,
	0x24, 0xf6, 0x9d, 0xed, 0x2d, 0x16, 0x6f, 0xaa, 0x15, 0xcf, 0x87, 0xc1, 0xdd, 0xcf, 0x04, 0x66,
	0x5e, 0xbd, 0x1c, 0x09, 0x7c, 0x80, 0x7c, 0x6f, 0x9d, 0xee, 0xb5, 0x35, 0x2c, 0xe1, 0x49, 0x5d,
	0x2e, 0xb9, 0x88, 0xb8, 0xf8, 0x8b, 0x8a, 0xd7, 0xc0, 0xc9, 0xf8, 0x03, 0x19, 0x5c, 0x86, 0x28,
	0x36, 0xe1, 0x49, 0x5d, 0xc8, 0x93, 0xc5, 0x15, 0xcc, 0xc8, 0xa8, 0x26, 0xee, 0x4e, 0xcf, 0xdc,
	0x5d, 0x92, 0x51, 0x27, 0x83, 0xb7, 0x00, 0xc7, 0x3e, 0x1b, 0xab, 0x88, 0x4d, 0x79, 0x52, 0x57,
	0xb2, 0xf0, 0x2f, 0x2b, 0xab, 0x08, 0x17, 0x90, 0x3b, 0xfa, 0xa4, 0x4e, 0xf7, 0x23, 0xbb, 0xf0,
	0xc3, 0xe8, 0xf1, 0x1e, 0x32, 0x0f, 0x3a, 0x96, 0xf1, 0xb4, 0x2e, 0x97, 0xf3, 0x7f, 0x92, 0x65,
	0xc0, 0x16, 0x4f, 0x90, 0xc7, 0xdc, 0x6b, 0x48, 0x3b, 0xfb, 0xe5, 0xef, 0x51, 0xc9, 0x83, 0xc4,
	0x1b, 0xc8, 0x36, 0x76, 0x3b, 0xec, 0x8c, 0xef, 0x59, 0xc9, 0xe0, 0x10, 0x61, 0xfa, 0xae, 0xb7,
	0xe4, 0xeb, 0x15, 0xd2, 0xeb, 0xc7, 0x2b, 0xa8, 0xba, 0x41, 0x8c, 0x6b, 0xa3, 0xe8, 0x5b, 0x8c,
	0xaa, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x09, 0x12, 0x28, 0x76, 0x99, 0x01, 0x00, 0x00,
}

const ()
