// Code generated by go generate wire_value.go; DO NOT EDIT.
// Source: descriptors from github.com/ydb-platform/ydb-go-genproto.

package query

import "google.golang.org/protobuf/encoding/protowire"

const (
	wirePartResultSetField    protowire.Number = 4 // Ydb.Query.ExecuteQueryResponsePart.result_set; message
	wirePartResultSetWireType protowire.Type   = protowire.BytesType
	wireResultSetRowsField    protowire.Number = 2 // Ydb.ResultSet.rows; message, repeated
	wireResultSetRowsWireType protowire.Type   = protowire.BytesType
	wireValueItemsField       protowire.Number = 12 // Ydb.Value.items; message, repeated
	wireValueItemsWireType    protowire.Type   = protowire.BytesType
	wireValueBoolField        protowire.Number = 1 // Ydb.Value.bool_value; bool, oneof
	wireValueBoolWireType     protowire.Type   = protowire.VarintType
	wireValueInt32Field       protowire.Number = 2 // Ydb.Value.int32_value; sfixed32, oneof
	wireValueInt32WireType    protowire.Type   = protowire.Fixed32Type
	wireValueUint32Field      protowire.Number = 3 // Ydb.Value.uint32_value; fixed32, oneof
	wireValueUint32WireType   protowire.Type   = protowire.Fixed32Type
	wireValueInt64Field       protowire.Number = 4 // Ydb.Value.int64_value; sfixed64, oneof
	wireValueInt64WireType    protowire.Type   = protowire.Fixed64Type
	wireValueUint64Field      protowire.Number = 5 // Ydb.Value.uint64_value; fixed64, oneof
	wireValueUint64WireType   protowire.Type   = protowire.Fixed64Type
	wireValueFloatField       protowire.Number = 6 // Ydb.Value.float_value; float, oneof
	wireValueFloatWireType    protowire.Type   = protowire.Fixed32Type
	wireValueDoubleField      protowire.Number = 7 // Ydb.Value.double_value; double, oneof
	wireValueDoubleWireType   protowire.Type   = protowire.Fixed64Type
	wireValueBytesField       protowire.Number = 8 // Ydb.Value.bytes_value; bytes, oneof
	wireValueBytesWireType    protowire.Type   = protowire.BytesType
	wireValueTextField        protowire.Number = 9 // Ydb.Value.text_value; string, oneof
	wireValueTextWireType     protowire.Type   = protowire.BytesType
	wireValueNullField        protowire.Number = 10 // Ydb.Value.null_flag_value; enum, oneof
	wireValueNullWireType     protowire.Type   = protowire.VarintType
	wireValueNestedField      protowire.Number = 11 // Ydb.Value.nested_value; message, oneof
	wireValueNestedWireType   protowire.Type   = protowire.BytesType
	wireValueLow128Field      protowire.Number = 15 // Ydb.Value.low_128; fixed64, oneof
	wireValueLow128WireType   protowire.Type   = protowire.Fixed64Type
)
