// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ydb_scripting.proto

package Ydb_Scripting

import (
	Ydb "github.com/yandex-cloud/ydb-go-sdk/api/protos/Ydb"
	Ydb_Operations "github.com/yandex-cloud/ydb-go-sdk/api/protos/Ydb_Operations"
	Ydb_Table "github.com/yandex-cloud/ydb-go-sdk/api/protos/Ydb_Table"
	Ydb_TableStats "github.com/yandex-cloud/ydb-go-sdk/api/protos/Ydb_TableStats"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExplainYqlRequest_Mode int32

const (
	ExplainYqlRequest_MODE_UNSPECIFIED ExplainYqlRequest_Mode = 0
	// PARSE = 1;
	ExplainYqlRequest_VALIDATE ExplainYqlRequest_Mode = 2
	ExplainYqlRequest_PLAN     ExplainYqlRequest_Mode = 3
)

var ExplainYqlRequest_Mode_name = map[int32]string{
	0: "MODE_UNSPECIFIED",
	2: "VALIDATE",
	3: "PLAN",
}

var ExplainYqlRequest_Mode_value = map[string]int32{
	"MODE_UNSPECIFIED": 0,
	"VALIDATE":         2,
	"PLAN":             3,
}

func (x ExplainYqlRequest_Mode) String() string {
	return proto.EnumName(ExplainYqlRequest_Mode_name, int32(x))
}

func (ExplainYqlRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{3, 0}
}

type ExecuteYqlRequest struct {
	OperationParams      *Ydb_Operations.OperationParams     `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty"`
	Script               string                              `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Parameters           map[string]*Ydb.TypedValue          `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CollectStats         Ydb_Table.QueryStatsCollection_Mode `protobuf:"varint,4,opt,name=collect_stats,json=collectStats,proto3,enum=Ydb.Table.QueryStatsCollection_Mode" json:"collect_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ExecuteYqlRequest) Reset()         { *m = ExecuteYqlRequest{} }
func (m *ExecuteYqlRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteYqlRequest) ProtoMessage()    {}
func (*ExecuteYqlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{0}
}

func (m *ExecuteYqlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteYqlRequest.Unmarshal(m, b)
}
func (m *ExecuteYqlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteYqlRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteYqlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteYqlRequest.Merge(m, src)
}
func (m *ExecuteYqlRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteYqlRequest.Size(m)
}
func (m *ExecuteYqlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteYqlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteYqlRequest proto.InternalMessageInfo

func (m *ExecuteYqlRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if m != nil {
		return m.OperationParams
	}
	return nil
}

func (m *ExecuteYqlRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *ExecuteYqlRequest) GetParameters() map[string]*Ydb.TypedValue {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ExecuteYqlRequest) GetCollectStats() Ydb_Table.QueryStatsCollection_Mode {
	if m != nil {
		return m.CollectStats
	}
	return Ydb_Table.QueryStatsCollection_STATS_COLLECTION_UNSPECIFIED
}

type ExecuteYqlResponse struct {
	Operation            *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExecuteYqlResponse) Reset()         { *m = ExecuteYqlResponse{} }
func (m *ExecuteYqlResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteYqlResponse) ProtoMessage()    {}
func (*ExecuteYqlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{1}
}

func (m *ExecuteYqlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteYqlResponse.Unmarshal(m, b)
}
func (m *ExecuteYqlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteYqlResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteYqlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteYqlResponse.Merge(m, src)
}
func (m *ExecuteYqlResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteYqlResponse.Size(m)
}
func (m *ExecuteYqlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteYqlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteYqlResponse proto.InternalMessageInfo

func (m *ExecuteYqlResponse) GetOperation() *Ydb_Operations.Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type ExecuteYqlResult struct {
	ResultSets           []*Ydb.ResultSet           `protobuf:"bytes,1,rep,name=result_sets,json=resultSets,proto3" json:"result_sets,omitempty"`
	QueryStats           *Ydb_TableStats.QueryStats `protobuf:"bytes,2,opt,name=query_stats,json=queryStats,proto3" json:"query_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ExecuteYqlResult) Reset()         { *m = ExecuteYqlResult{} }
func (m *ExecuteYqlResult) String() string { return proto.CompactTextString(m) }
func (*ExecuteYqlResult) ProtoMessage()    {}
func (*ExecuteYqlResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{2}
}

func (m *ExecuteYqlResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteYqlResult.Unmarshal(m, b)
}
func (m *ExecuteYqlResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteYqlResult.Marshal(b, m, deterministic)
}
func (m *ExecuteYqlResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteYqlResult.Merge(m, src)
}
func (m *ExecuteYqlResult) XXX_Size() int {
	return xxx_messageInfo_ExecuteYqlResult.Size(m)
}
func (m *ExecuteYqlResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteYqlResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteYqlResult proto.InternalMessageInfo

func (m *ExecuteYqlResult) GetResultSets() []*Ydb.ResultSet {
	if m != nil {
		return m.ResultSets
	}
	return nil
}

func (m *ExecuteYqlResult) GetQueryStats() *Ydb_TableStats.QueryStats {
	if m != nil {
		return m.QueryStats
	}
	return nil
}

type ExplainYqlRequest struct {
	OperationParams      *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty"`
	Script               string                          `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Mode                 ExplainYqlRequest_Mode          `protobuf:"varint,3,opt,name=mode,proto3,enum=Ydb.Scripting.ExplainYqlRequest_Mode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ExplainYqlRequest) Reset()         { *m = ExplainYqlRequest{} }
func (m *ExplainYqlRequest) String() string { return proto.CompactTextString(m) }
func (*ExplainYqlRequest) ProtoMessage()    {}
func (*ExplainYqlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{3}
}

func (m *ExplainYqlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExplainYqlRequest.Unmarshal(m, b)
}
func (m *ExplainYqlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExplainYqlRequest.Marshal(b, m, deterministic)
}
func (m *ExplainYqlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExplainYqlRequest.Merge(m, src)
}
func (m *ExplainYqlRequest) XXX_Size() int {
	return xxx_messageInfo_ExplainYqlRequest.Size(m)
}
func (m *ExplainYqlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExplainYqlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExplainYqlRequest proto.InternalMessageInfo

func (m *ExplainYqlRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if m != nil {
		return m.OperationParams
	}
	return nil
}

func (m *ExplainYqlRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *ExplainYqlRequest) GetMode() ExplainYqlRequest_Mode {
	if m != nil {
		return m.Mode
	}
	return ExplainYqlRequest_MODE_UNSPECIFIED
}

type ExplainYqlResponse struct {
	Operation            *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExplainYqlResponse) Reset()         { *m = ExplainYqlResponse{} }
func (m *ExplainYqlResponse) String() string { return proto.CompactTextString(m) }
func (*ExplainYqlResponse) ProtoMessage()    {}
func (*ExplainYqlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{4}
}

func (m *ExplainYqlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExplainYqlResponse.Unmarshal(m, b)
}
func (m *ExplainYqlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExplainYqlResponse.Marshal(b, m, deterministic)
}
func (m *ExplainYqlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExplainYqlResponse.Merge(m, src)
}
func (m *ExplainYqlResponse) XXX_Size() int {
	return xxx_messageInfo_ExplainYqlResponse.Size(m)
}
func (m *ExplainYqlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExplainYqlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExplainYqlResponse proto.InternalMessageInfo

func (m *ExplainYqlResponse) GetOperation() *Ydb_Operations.Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type ExplainYqlResult struct {
	ParametersTypes      map[string]*Ydb.Type `protobuf:"bytes,1,rep,name=parameters_types,json=parametersTypes,proto3" json:"parameters_types,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Plan                 string               `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExplainYqlResult) Reset()         { *m = ExplainYqlResult{} }
func (m *ExplainYqlResult) String() string { return proto.CompactTextString(m) }
func (*ExplainYqlResult) ProtoMessage()    {}
func (*ExplainYqlResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{5}
}

func (m *ExplainYqlResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExplainYqlResult.Unmarshal(m, b)
}
func (m *ExplainYqlResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExplainYqlResult.Marshal(b, m, deterministic)
}
func (m *ExplainYqlResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExplainYqlResult.Merge(m, src)
}
func (m *ExplainYqlResult) XXX_Size() int {
	return xxx_messageInfo_ExplainYqlResult.Size(m)
}
func (m *ExplainYqlResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExplainYqlResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExplainYqlResult proto.InternalMessageInfo

func (m *ExplainYqlResult) GetParametersTypes() map[string]*Ydb.Type {
	if m != nil {
		return m.ParametersTypes
	}
	return nil
}

func (m *ExplainYqlResult) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func init() {
	proto.RegisterEnum("Ydb.Scripting.ExplainYqlRequest_Mode", ExplainYqlRequest_Mode_name, ExplainYqlRequest_Mode_value)
	proto.RegisterType((*ExecuteYqlRequest)(nil), "Ydb.Scripting.ExecuteYqlRequest")
	proto.RegisterMapType((map[string]*Ydb.TypedValue)(nil), "Ydb.Scripting.ExecuteYqlRequest.ParametersEntry")
	proto.RegisterType((*ExecuteYqlResponse)(nil), "Ydb.Scripting.ExecuteYqlResponse")
	proto.RegisterType((*ExecuteYqlResult)(nil), "Ydb.Scripting.ExecuteYqlResult")
	proto.RegisterType((*ExplainYqlRequest)(nil), "Ydb.Scripting.ExplainYqlRequest")
	proto.RegisterType((*ExplainYqlResponse)(nil), "Ydb.Scripting.ExplainYqlResponse")
	proto.RegisterType((*ExplainYqlResult)(nil), "Ydb.Scripting.ExplainYqlResult")
	proto.RegisterMapType((map[string]*Ydb.Type)(nil), "Ydb.Scripting.ExplainYqlResult.ParametersTypesEntry")
}

func init() { proto.RegisterFile("ydb_scripting.proto", fileDescriptor_49d60dbac494bf1d) }

var fileDescriptor_49d60dbac494bf1d = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xad, 0x6c, 0x37, 0xc4, 0xe3, 0x24, 0x56, 0xb7, 0xa1, 0xa8, 0xbe, 0xc4, 0x98, 0x06, 0x7c,
	0x28, 0xeb, 0xe2, 0x06, 0xfa, 0x75, 0x72, 0x62, 0x15, 0x5c, 0x62, 0x47, 0x95, 0xd3, 0x40, 0x4e,
	0x42, 0x1f, 0x4b, 0x11, 0x96, 0xa5, 0xb5, 0x76, 0x55, 0xa2, 0x5b, 0x7f, 0x65, 0x7f, 0x41, 0x0f,
	0xfd, 0x09, 0x3d, 0x96, 0x5d, 0xc9, 0xb2, 0x94, 0xa4, 0xa6, 0x50, 0xc8, 0x6d, 0x34, 0xf3, 0x66,
	0xb4, 0xf3, 0xde, 0xdb, 0x85, 0xa7, 0xa9, 0xe7, 0x58, 0xcc, 0x8d, 0x7d, 0xca, 0xfd, 0xf0, 0x2b,
	0xa6, 0x71, 0xc4, 0x23, 0xb4, 0x7f, 0xed, 0x39, 0x78, 0xbe, 0x4e, 0x76, 0x5e, 0x2e, 0xfc, 0x85,
	0xbf, 0x8c, 0x07, 0x34, 0x71, 0x02, 0xdf, 0x1d, 0xd8, 0xd4, 0x1f, 0x48, 0x1c, 0x1b, 0x88, 0xe6,
	0x88, 0x92, 0xd8, 0xe6, 0x7e, 0x14, 0x66, 0xcd, 0x9d, 0xfe, 0x56, 0xf4, 0x37, 0x3b, 0x48, 0xc8,
	0x3f, 0x21, 0xb9, 0xed, 0x04, 0x6b, 0x24, 0xde, 0x8a, 0x5c, 0x25, 0x24, 0x4e, 0x2d, 0xc6, 0x6d,
	0xce, 0x32, 0x7c, 0xef, 0x67, 0x0d, 0x9e, 0xe8, 0x37, 0xc4, 0x4d, 0x38, 0xb9, 0x5e, 0x05, 0x26,
	0x59, 0x25, 0x84, 0x71, 0xf4, 0x09, 0xd4, 0xe2, 0xb0, 0x16, 0xb5, 0x63, 0x7b, 0xc9, 0x34, 0xa5,
	0xab, 0xf4, 0x5b, 0xc3, 0x23, 0x2c, 0x36, 0xbe, 0x58, 0x17, 0xd9, 0x26, 0x34, 0x24, 0xcc, 0x6c,
	0x47, 0xd5, 0x04, 0x7a, 0x06, 0x3b, 0x19, 0x6b, 0x5a, 0xad, 0xab, 0xf4, 0x9b, 0x66, 0xfe, 0x85,
	0x0c, 0x00, 0x39, 0x99, 0x70, 0x12, 0x33, 0xad, 0xde, 0xad, 0xf7, 0x5b, 0xc3, 0x57, 0xb8, 0xc2,
	0x27, 0xbe, 0x73, 0x32, 0x6c, 0x14, 0x2d, 0x7a, 0xc8, 0xe3, 0xd4, 0x2c, 0xcd, 0x40, 0x13, 0xd8,
	0x77, 0xa3, 0x20, 0x20, 0x2e, 0xcf, 0x56, 0xd4, 0x1a, 0x5d, 0xa5, 0x7f, 0x30, 0x7c, 0x21, 0x87,
	0x5e, 0x4a, 0x92, 0x3e, 0x0b, 0x02, 0xe6, 0xa2, 0x78, 0x96, 0x21, 0x85, 0x1a, 0xd3, 0xc8, 0x23,
	0xe6, 0x5e, 0xde, 0x2a, 0x8b, 0x9d, 0x19, 0xb4, 0x6f, 0xfd, 0x09, 0xa9, 0x50, 0x5f, 0x90, 0x54,
	0xd2, 0xd0, 0x34, 0x45, 0x88, 0x8e, 0xe1, 0xb1, 0x14, 0x49, 0x2e, 0xd6, 0x1a, 0xb6, 0xb3, 0xff,
	0xa4, 0x94, 0x78, 0x57, 0x22, 0x6d, 0x66, 0xd5, 0xf7, 0xb5, 0xb7, 0x4a, 0x6f, 0x0a, 0xa8, 0xbc,
	0x0b, 0xa3, 0x51, 0xc8, 0x08, 0x7a, 0x03, 0xcd, 0x82, 0xad, 0x9c, 0xdf, 0xe7, 0x7f, 0xe5, 0xd7,
	0xdc, 0x60, 0x7b, 0xdf, 0x15, 0x50, 0x2b, 0xf3, 0x92, 0x80, 0xa3, 0x01, 0xb4, 0x62, 0x19, 0x59,
	0x8c, 0x70, 0xa1, 0x97, 0x60, 0xf4, 0x40, 0xce, 0xcb, 0x10, 0x73, 0xc2, 0x4d, 0x88, 0xd7, 0x21,
	0x43, 0x1f, 0xa0, 0x55, 0x32, 0x44, 0xbe, 0x45, 0x67, 0xc3, 0x96, 0xa4, 0xa2, 0x44, 0x99, 0x09,
	0xab, 0x22, 0xee, 0xfd, 0x52, 0x84, 0x71, 0x68, 0x60, 0xfb, 0xe1, 0x03, 0x1b, 0xe7, 0x1d, 0x34,
	0x96, 0x91, 0x47, 0xb4, 0xba, 0x54, 0xf7, 0xf8, 0x8e, 0x65, 0x6e, 0x9d, 0x29, 0x93, 0x57, 0xb6,
	0xf4, 0x4e, 0xa0, 0x21, 0xbe, 0xd0, 0x21, 0xa8, 0xd3, 0x8b, 0xb1, 0x6e, 0x7d, 0x99, 0xcd, 0x0d,
	0xfd, 0x6c, 0xf2, 0x71, 0xa2, 0x8f, 0xd5, 0x47, 0x68, 0x0f, 0x76, 0xaf, 0x46, 0xe7, 0x93, 0xf1,
	0xe8, 0x52, 0x57, 0x6b, 0x68, 0x17, 0x1a, 0xc6, 0xf9, 0x68, 0xa6, 0xd6, 0x33, 0xf1, 0x36, 0x53,
	0xff, 0x57, 0xbc, 0x1f, 0x52, 0xbc, 0xd2, 0x3c, 0x21, 0x9e, 0x05, 0xea, 0xc6, 0xc9, 0x16, 0x4f,
	0x29, 0x59, 0x2b, 0x78, 0xb2, 0x65, 0x41, 0xd1, 0x5a, 0xba, 0x12, 0xc2, 0x7b, 0xf9, 0xbd, 0x68,
	0xd3, 0x6a, 0x16, 0x21, 0x68, 0xd0, 0xc0, 0x0e, 0x73, 0x2e, 0x65, 0xdc, 0x99, 0xc2, 0xe1, 0x7d,
	0xcd, 0xf7, 0x58, 0xfd, 0xa8, 0x6a, 0xf5, 0x66, 0x61, 0xf5, 0x92, 0xc9, 0x4f, 0x31, 0x68, 0x6e,
	0xb4, 0xc4, 0xa9, 0x1d, 0x7a, 0xe4, 0x06, 0xa7, 0x9e, 0x83, 0x8b, 0xe7, 0xf2, 0xb4, 0x5d, 0x2c,
	0x60, 0xc8, 0xe7, 0xe8, 0xb7, 0xa2, 0x38, 0x3b, 0xf2, 0x09, 0x7a, 0xfd, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x75, 0x0a, 0x5a, 0xcf, 0x5a, 0x05, 0x00, 0x00,
}

const ()

// SetOperationParams implements ydb generic interface for setting
// operation parameters inside driver implementation.
func (m *ExecuteYqlRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	m.OperationParams = v
}

// SetOperationParams implements ydb generic interface for setting
// operation parameters inside driver implementation.
func (m *ExplainYqlRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	m.OperationParams = v
}
