// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ydb_scripting.proto

package Ydb_Scripting

import (
	Ydb "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb"
	Ydb_Issue "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb_Issue"
	Ydb_Operations "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb_Operations"
	Ydb_Table "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb_Table"
	Ydb_TableStats "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb_TableStats"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExplainYqlRequest_Mode int32

const (
	ExplainYqlRequest_MODE_UNSPECIFIED ExplainYqlRequest_Mode = 0
	// PARSE = 1;
	ExplainYqlRequest_VALIDATE ExplainYqlRequest_Mode = 2
	ExplainYqlRequest_PLAN     ExplainYqlRequest_Mode = 3
)

var ExplainYqlRequest_Mode_name = map[int32]string{
	0: "MODE_UNSPECIFIED",
	2: "VALIDATE",
	3: "PLAN",
}

var ExplainYqlRequest_Mode_value = map[string]int32{
	"MODE_UNSPECIFIED": 0,
	"VALIDATE":         2,
	"PLAN":             3,
}

func (x ExplainYqlRequest_Mode) String() string {
	return proto.EnumName(ExplainYqlRequest_Mode_name, int32(x))
}

func (ExplainYqlRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{5, 0}
}

type ExecuteYqlRequest struct {
	OperationParams      *Ydb_Operations.OperationParams     `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty"`
	Script               string                              `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Parameters           map[string]*Ydb.TypedValue          `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CollectStats         Ydb_Table.QueryStatsCollection_Mode `protobuf:"varint,4,opt,name=collect_stats,json=collectStats,proto3,enum=Ydb.Table.QueryStatsCollection_Mode" json:"collect_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ExecuteYqlRequest) Reset()         { *m = ExecuteYqlRequest{} }
func (m *ExecuteYqlRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteYqlRequest) ProtoMessage()    {}
func (*ExecuteYqlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{0}
}

func (m *ExecuteYqlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteYqlRequest.Unmarshal(m, b)
}
func (m *ExecuteYqlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteYqlRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteYqlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteYqlRequest.Merge(m, src)
}
func (m *ExecuteYqlRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteYqlRequest.Size(m)
}
func (m *ExecuteYqlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteYqlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteYqlRequest proto.InternalMessageInfo

func (m *ExecuteYqlRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if m != nil {
		return m.OperationParams
	}
	return nil
}

func (m *ExecuteYqlRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *ExecuteYqlRequest) GetParameters() map[string]*Ydb.TypedValue {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ExecuteYqlRequest) GetCollectStats() Ydb_Table.QueryStatsCollection_Mode {
	if m != nil {
		return m.CollectStats
	}
	return Ydb_Table.QueryStatsCollection_STATS_COLLECTION_UNSPECIFIED
}

type ExecuteYqlResponse struct {
	Operation            *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExecuteYqlResponse) Reset()         { *m = ExecuteYqlResponse{} }
func (m *ExecuteYqlResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteYqlResponse) ProtoMessage()    {}
func (*ExecuteYqlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{1}
}

func (m *ExecuteYqlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteYqlResponse.Unmarshal(m, b)
}
func (m *ExecuteYqlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteYqlResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteYqlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteYqlResponse.Merge(m, src)
}
func (m *ExecuteYqlResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteYqlResponse.Size(m)
}
func (m *ExecuteYqlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteYqlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteYqlResponse proto.InternalMessageInfo

func (m *ExecuteYqlResponse) GetOperation() *Ydb_Operations.Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type ExecuteYqlResult struct {
	ResultSets           []*Ydb.ResultSet           `protobuf:"bytes,1,rep,name=result_sets,json=resultSets,proto3" json:"result_sets,omitempty"`
	QueryStats           *Ydb_TableStats.QueryStats `protobuf:"bytes,2,opt,name=query_stats,json=queryStats,proto3" json:"query_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ExecuteYqlResult) Reset()         { *m = ExecuteYqlResult{} }
func (m *ExecuteYqlResult) String() string { return proto.CompactTextString(m) }
func (*ExecuteYqlResult) ProtoMessage()    {}
func (*ExecuteYqlResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{2}
}

func (m *ExecuteYqlResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteYqlResult.Unmarshal(m, b)
}
func (m *ExecuteYqlResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteYqlResult.Marshal(b, m, deterministic)
}
func (m *ExecuteYqlResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteYqlResult.Merge(m, src)
}
func (m *ExecuteYqlResult) XXX_Size() int {
	return xxx_messageInfo_ExecuteYqlResult.Size(m)
}
func (m *ExecuteYqlResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteYqlResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteYqlResult proto.InternalMessageInfo

func (m *ExecuteYqlResult) GetResultSets() []*Ydb.ResultSet {
	if m != nil {
		return m.ResultSets
	}
	return nil
}

func (m *ExecuteYqlResult) GetQueryStats() *Ydb_TableStats.QueryStats {
	if m != nil {
		return m.QueryStats
	}
	return nil
}

// Response for StreamExecuteYql is a stream of ExecuteYqlPartialResponse messages.
// These responses can contain ExecuteYqlPartialResult messages with
// results (or result parts) for data or scan queries in the script.
// YqlScript can have multiple results (result sets).
// Each result set has an index (starting at 0).
type ExecuteYqlPartialResponse struct {
	Status               Ydb.StatusIds_StatusCode  `protobuf:"varint,1,opt,name=status,proto3,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues               []*Ydb_Issue.IssueMessage `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	Result               *ExecuteYqlPartialResult  `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExecuteYqlPartialResponse) Reset()         { *m = ExecuteYqlPartialResponse{} }
func (m *ExecuteYqlPartialResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteYqlPartialResponse) ProtoMessage()    {}
func (*ExecuteYqlPartialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{3}
}

func (m *ExecuteYqlPartialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteYqlPartialResponse.Unmarshal(m, b)
}
func (m *ExecuteYqlPartialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteYqlPartialResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteYqlPartialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteYqlPartialResponse.Merge(m, src)
}
func (m *ExecuteYqlPartialResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteYqlPartialResponse.Size(m)
}
func (m *ExecuteYqlPartialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteYqlPartialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteYqlPartialResponse proto.InternalMessageInfo

func (m *ExecuteYqlPartialResponse) GetStatus() Ydb.StatusIds_StatusCode {
	if m != nil {
		return m.Status
	}
	return Ydb.StatusIds_STATUS_CODE_UNSPECIFIED
}

func (m *ExecuteYqlPartialResponse) GetIssues() []*Ydb_Issue.IssueMessage {
	if m != nil {
		return m.Issues
	}
	return nil
}

func (m *ExecuteYqlPartialResponse) GetResult() *ExecuteYqlPartialResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// Contains result set (or a result set part) for one data or scan query in the script.
// One result set can be split into several responses with same result_index.
// Only the final response can contain query stats.
type ExecuteYqlPartialResult struct {
	// Index of current result
	ResultSetIndex uint32 `protobuf:"varint,1,opt,name=result_set_index,json=resultSetIndex,proto3" json:"result_set_index,omitempty"`
	// Result set (or a result set part) for one data or scan query
	ResultSet            *Ydb.ResultSet             `protobuf:"bytes,2,opt,name=result_set,json=resultSet,proto3" json:"result_set,omitempty"`
	QueryStats           *Ydb_TableStats.QueryStats `protobuf:"bytes,3,opt,name=query_stats,json=queryStats,proto3" json:"query_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ExecuteYqlPartialResult) Reset()         { *m = ExecuteYqlPartialResult{} }
func (m *ExecuteYqlPartialResult) String() string { return proto.CompactTextString(m) }
func (*ExecuteYqlPartialResult) ProtoMessage()    {}
func (*ExecuteYqlPartialResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{4}
}

func (m *ExecuteYqlPartialResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteYqlPartialResult.Unmarshal(m, b)
}
func (m *ExecuteYqlPartialResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteYqlPartialResult.Marshal(b, m, deterministic)
}
func (m *ExecuteYqlPartialResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteYqlPartialResult.Merge(m, src)
}
func (m *ExecuteYqlPartialResult) XXX_Size() int {
	return xxx_messageInfo_ExecuteYqlPartialResult.Size(m)
}
func (m *ExecuteYqlPartialResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteYqlPartialResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteYqlPartialResult proto.InternalMessageInfo

func (m *ExecuteYqlPartialResult) GetResultSetIndex() uint32 {
	if m != nil {
		return m.ResultSetIndex
	}
	return 0
}

func (m *ExecuteYqlPartialResult) GetResultSet() *Ydb.ResultSet {
	if m != nil {
		return m.ResultSet
	}
	return nil
}

func (m *ExecuteYqlPartialResult) GetQueryStats() *Ydb_TableStats.QueryStats {
	if m != nil {
		return m.QueryStats
	}
	return nil
}

type ExplainYqlRequest struct {
	OperationParams      *Ydb_Operations.OperationParams `protobuf:"bytes,1,opt,name=operation_params,json=operationParams,proto3" json:"operation_params,omitempty"`
	Script               string                          `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Mode                 ExplainYqlRequest_Mode          `protobuf:"varint,3,opt,name=mode,proto3,enum=Ydb.Scripting.ExplainYqlRequest_Mode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ExplainYqlRequest) Reset()         { *m = ExplainYqlRequest{} }
func (m *ExplainYqlRequest) String() string { return proto.CompactTextString(m) }
func (*ExplainYqlRequest) ProtoMessage()    {}
func (*ExplainYqlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{5}
}

func (m *ExplainYqlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExplainYqlRequest.Unmarshal(m, b)
}
func (m *ExplainYqlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExplainYqlRequest.Marshal(b, m, deterministic)
}
func (m *ExplainYqlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExplainYqlRequest.Merge(m, src)
}
func (m *ExplainYqlRequest) XXX_Size() int {
	return xxx_messageInfo_ExplainYqlRequest.Size(m)
}
func (m *ExplainYqlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExplainYqlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExplainYqlRequest proto.InternalMessageInfo

func (m *ExplainYqlRequest) GetOperationParams() *Ydb_Operations.OperationParams {
	if m != nil {
		return m.OperationParams
	}
	return nil
}

func (m *ExplainYqlRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *ExplainYqlRequest) GetMode() ExplainYqlRequest_Mode {
	if m != nil {
		return m.Mode
	}
	return ExplainYqlRequest_MODE_UNSPECIFIED
}

type ExplainYqlResponse struct {
	Operation            *Ydb_Operations.Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ExplainYqlResponse) Reset()         { *m = ExplainYqlResponse{} }
func (m *ExplainYqlResponse) String() string { return proto.CompactTextString(m) }
func (*ExplainYqlResponse) ProtoMessage()    {}
func (*ExplainYqlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{6}
}

func (m *ExplainYqlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExplainYqlResponse.Unmarshal(m, b)
}
func (m *ExplainYqlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExplainYqlResponse.Marshal(b, m, deterministic)
}
func (m *ExplainYqlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExplainYqlResponse.Merge(m, src)
}
func (m *ExplainYqlResponse) XXX_Size() int {
	return xxx_messageInfo_ExplainYqlResponse.Size(m)
}
func (m *ExplainYqlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExplainYqlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExplainYqlResponse proto.InternalMessageInfo

func (m *ExplainYqlResponse) GetOperation() *Ydb_Operations.Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type ExplainYqlResult struct {
	ParametersTypes      map[string]*Ydb.Type `protobuf:"bytes,1,rep,name=parameters_types,json=parametersTypes,proto3" json:"parameters_types,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Plan                 string               `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExplainYqlResult) Reset()         { *m = ExplainYqlResult{} }
func (m *ExplainYqlResult) String() string { return proto.CompactTextString(m) }
func (*ExplainYqlResult) ProtoMessage()    {}
func (*ExplainYqlResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_49d60dbac494bf1d, []int{7}
}

func (m *ExplainYqlResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExplainYqlResult.Unmarshal(m, b)
}
func (m *ExplainYqlResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExplainYqlResult.Marshal(b, m, deterministic)
}
func (m *ExplainYqlResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExplainYqlResult.Merge(m, src)
}
func (m *ExplainYqlResult) XXX_Size() int {
	return xxx_messageInfo_ExplainYqlResult.Size(m)
}
func (m *ExplainYqlResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExplainYqlResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExplainYqlResult proto.InternalMessageInfo

func (m *ExplainYqlResult) GetParametersTypes() map[string]*Ydb.Type {
	if m != nil {
		return m.ParametersTypes
	}
	return nil
}

func (m *ExplainYqlResult) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func init() {
	proto.RegisterEnum("Ydb.Scripting.ExplainYqlRequest_Mode", ExplainYqlRequest_Mode_name, ExplainYqlRequest_Mode_value)
	proto.RegisterType((*ExecuteYqlRequest)(nil), "Ydb.Scripting.ExecuteYqlRequest")
	proto.RegisterMapType((map[string]*Ydb.TypedValue)(nil), "Ydb.Scripting.ExecuteYqlRequest.ParametersEntry")
	proto.RegisterType((*ExecuteYqlResponse)(nil), "Ydb.Scripting.ExecuteYqlResponse")
	proto.RegisterType((*ExecuteYqlResult)(nil), "Ydb.Scripting.ExecuteYqlResult")
	proto.RegisterType((*ExecuteYqlPartialResponse)(nil), "Ydb.Scripting.ExecuteYqlPartialResponse")
	proto.RegisterType((*ExecuteYqlPartialResult)(nil), "Ydb.Scripting.ExecuteYqlPartialResult")
	proto.RegisterType((*ExplainYqlRequest)(nil), "Ydb.Scripting.ExplainYqlRequest")
	proto.RegisterType((*ExplainYqlResponse)(nil), "Ydb.Scripting.ExplainYqlResponse")
	proto.RegisterType((*ExplainYqlResult)(nil), "Ydb.Scripting.ExplainYqlResult")
	proto.RegisterMapType((map[string]*Ydb.Type)(nil), "Ydb.Scripting.ExplainYqlResult.ParametersTypesEntry")
}

func init() { proto.RegisterFile("ydb_scripting.proto", fileDescriptor_49d60dbac494bf1d) }

var fileDescriptor_49d60dbac494bf1d = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0x88, 0x9a, 0x49, 0x9b, 0x98, 0xa5, 0xa2, 0x69, 0x2e, 0x8d, 0x22, 0x8a, 0x72,
	0x00, 0xbb, 0x84, 0x4a, 0xfc, 0x49, 0x48, 0xfd, 0x09, 0x92, 0x51, 0xd3, 0x1a, 0xa7, 0x54, 0xea,
	0xc9, 0x72, 0xec, 0x55, 0x65, 0xd5, 0xb1, 0x1d, 0xef, 0x1a, 0xd5, 0x37, 0xde, 0x88, 0x47, 0xe0,
	0x2d, 0x78, 0x02, 0x0e, 0x3c, 0x02, 0x47, 0xb4, 0xeb, 0x8d, 0xed, 0xa4, 0x4d, 0x04, 0x42, 0xe2,
	0x12, 0x4d, 0x66, 0xbf, 0x6f, 0x76, 0xe6, 0xdb, 0x99, 0x31, 0x3c, 0x4c, 0x9c, 0xb1, 0x49, 0xec,
	0xc8, 0x0d, 0xa9, 0xeb, 0x5f, 0x29, 0x61, 0x14, 0xd0, 0x00, 0x6d, 0x5c, 0x3a, 0x63, 0x65, 0x34,
	0x73, 0xb6, 0x9f, 0x5e, 0xbb, 0xd7, 0xee, 0x24, 0x52, 0xc3, 0x78, 0xec, 0xb9, 0xb6, 0x6a, 0x85,
	0xae, 0xca, 0x71, 0x44, 0x65, 0xe4, 0x20, 0xc4, 0x91, 0x45, 0xdd, 0xc0, 0x4f, 0xc9, 0xed, 0xde,
	0x4a, 0xf4, 0x67, 0xcb, 0x8b, 0xf1, 0x1f, 0x21, 0xa9, 0x35, 0xf6, 0x66, 0x48, 0x65, 0x25, 0x72,
	0x1a, 0xe3, 0x28, 0x31, 0x09, 0xb5, 0x28, 0x11, 0xf8, 0xbd, 0x95, 0x78, 0x97, 0x90, 0x18, 0x9b,
	0x13, 0x4c, 0x88, 0x75, 0x35, 0xbb, 0x41, 0x5d, 0xc9, 0x60, 0xb1, 0x63, 0x62, 0xda, 0x81, 0x83,
	0xc5, 0x15, 0xdd, 0x1f, 0x25, 0x78, 0x30, 0xb8, 0xc1, 0x76, 0x4c, 0xf1, 0xe5, 0xd4, 0x33, 0xf0,
	0x34, 0xc6, 0x84, 0xa2, 0x0f, 0x20, 0x67, 0x7a, 0x98, 0xa1, 0x15, 0x59, 0x13, 0xd2, 0x92, 0x3a,
	0x52, 0xaf, 0xde, 0xdf, 0x51, 0x98, 0xa8, 0x67, 0xb3, 0x43, 0x92, 0x9b, 0x3a, 0x87, 0x19, 0xcd,
	0x60, 0xde, 0x81, 0x1e, 0x41, 0x35, 0x7d, 0x98, 0x56, 0xa9, 0x23, 0xf5, 0x6a, 0x86, 0xf8, 0x87,
	0x74, 0x00, 0x1e, 0x19, 0x53, 0x1c, 0x91, 0x56, 0xb9, 0x53, 0xee, 0xd5, 0xfb, 0x7b, 0xca, 0xdc,
	0x93, 0x29, 0xb7, 0x32, 0x53, 0xf4, 0x8c, 0x32, 0xf0, 0x69, 0x94, 0x18, 0x85, 0x18, 0x48, 0x83,
	0x0d, 0x3b, 0xf0, 0x3c, 0x6c, 0xd3, 0x54, 0xc5, 0x56, 0xa5, 0x23, 0xf5, 0x1a, 0xfd, 0xc7, 0x3c,
	0xe8, 0x39, 0x7f, 0x87, 0x8f, 0x4c, 0xe3, 0x11, 0x3b, 0x3c, 0x4a, 0x91, 0xec, 0xc1, 0x87, 0x81,
	0x83, 0x8d, 0x75, 0x41, 0xe5, 0x87, 0xed, 0x53, 0x68, 0x2e, 0xdc, 0x84, 0x64, 0x28, 0x5f, 0xe3,
	0x84, 0xcb, 0x50, 0x33, 0x98, 0x89, 0x76, 0xe1, 0x3e, 0xef, 0x03, 0x5e, 0x58, 0xbd, 0xdf, 0x4c,
	0xef, 0x49, 0x42, 0xec, 0x5c, 0x30, 0xb7, 0x91, 0x9e, 0xbe, 0x29, 0xbd, 0x92, 0xba, 0x43, 0x40,
	0xc5, 0x5a, 0x48, 0x18, 0xf8, 0x04, 0xa3, 0x97, 0x50, 0xcb, 0xd4, 0x12, 0xfa, 0x6e, 0x2f, 0xd5,
	0xd7, 0xc8, 0xb1, 0xdd, 0x2f, 0x12, 0xc8, 0x73, 0xf1, 0x62, 0x8f, 0x22, 0x15, 0xea, 0x11, 0xb7,
	0x4c, 0x82, 0x29, 0x7b, 0x2f, 0xa6, 0x68, 0x83, 0xc7, 0x4b, 0x11, 0x23, 0x4c, 0x0d, 0x88, 0x66,
	0x26, 0x41, 0x6f, 0xa1, 0x5e, 0xe8, 0x39, 0x51, 0x45, 0x3b, 0x57, 0x8b, 0x4b, 0x51, 0x90, 0xcc,
	0x80, 0x69, 0x66, 0x77, 0xbf, 0x49, 0xb0, 0x9d, 0xa7, 0xa0, 0x5b, 0x11, 0x75, 0xad, 0xbc, 0xb2,
	0xe7, 0x50, 0x4d, 0x9b, 0x8d, 0x97, 0xd5, 0x10, 0x65, 0x8d, 0xb8, 0x4b, 0x73, 0x88, 0xb0, 0x8e,
	0x98, 0xf0, 0x02, 0x88, 0x54, 0xa8, 0xf2, 0x8e, 0x66, 0x89, 0xb0, 0xcc, 0xb7, 0x38, 0x45, 0x63,
	0xae, 0xf4, 0x77, 0x98, 0x76, 0xba, 0x21, 0x60, 0xe8, 0x1d, 0x54, 0xd3, 0x62, 0x5a, 0x65, 0x9e,
	0xf9, 0x93, 0xa5, 0xcd, 0x93, 0x67, 0x17, 0x7b, 0xd4, 0x10, 0xac, 0xee, 0x57, 0x09, 0xb6, 0x96,
	0x60, 0x50, 0x0f, 0xe4, 0x5c, 0x4b, 0xd3, 0xf5, 0x1d, 0x7c, 0xc3, 0x2b, 0xd9, 0x30, 0x1a, 0x99,
	0x80, 0x1a, 0xf3, 0xa2, 0x67, 0x00, 0x39, 0x52, 0x68, 0xb8, 0x28, 0x7a, 0x2d, 0xe3, 0x2c, 0x6a,
	0x5e, 0xfe, 0x2b, 0xcd, 0x7f, 0x4a, 0x6c, 0x58, 0x43, 0xcf, 0x72, 0xfd, 0xff, 0x3c, 0xac, 0xaf,
	0xa1, 0x32, 0x09, 0x1c, 0xcc, 0xf3, 0x6d, 0xf4, 0x77, 0x6f, 0x29, 0xbd, 0x90, 0x53, 0x3a, 0x52,
	0x9c, 0xd2, 0xdd, 0x87, 0x0a, 0xfb, 0x87, 0x36, 0x41, 0x1e, 0x9e, 0x1d, 0x0f, 0xcc, 0x4f, 0xa7,
	0x23, 0x7d, 0x70, 0xa4, 0xbd, 0xd7, 0x06, 0xc7, 0xf2, 0x3d, 0xb4, 0x0e, 0x6b, 0x17, 0x07, 0x27,
	0xda, 0xf1, 0xc1, 0xf9, 0x40, 0x2e, 0xa1, 0x35, 0xa8, 0xe8, 0x27, 0x07, 0xa7, 0x72, 0x39, 0x1d,
	0x98, 0x3c, 0xea, 0xbf, 0x0e, 0xcc, 0x77, 0x3e, 0x30, 0x85, 0x78, 0xec, 0x91, 0x4d, 0x90, 0xf3,
	0xed, 0x61, 0xd2, 0x24, 0xc4, 0xb3, 0xa9, 0xd9, 0x5f, 0x51, 0x20, 0xa3, 0x16, 0xd6, 0x10, 0x9b,
	0x77, 0xb1, 0x8b, 0x9a, 0xe1, 0xbc, 0x17, 0x21, 0xa8, 0x84, 0x9e, 0xe5, 0x0b, 0x2d, 0xb9, 0xdd,
	0x1e, 0xc2, 0xe6, 0x5d, 0xe4, 0x3b, 0xd6, 0xcb, 0xce, 0xfc, 0x7a, 0xa9, 0x65, 0xeb, 0xa5, 0xb0,
	0x58, 0x0e, 0x15, 0x68, 0xd9, 0xc1, 0x44, 0x49, 0x2c, 0xd6, 0x8c, 0x4a, 0xe2, 0x8c, 0x95, 0xec,
	0x2b, 0x78, 0xd8, 0xcc, 0x0a, 0xd0, 0xf9, 0x37, 0xe0, 0x97, 0x24, 0x8d, 0xab, 0x7c, 0xed, 0xbf,
	0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xe8, 0x61, 0x01, 0x31, 0x07, 0x00, 0x00,
}

// SetOperationParams implements ydb generic interface for setting
// operation parameters inside driver implementation.
func (m *ExecuteYqlRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	m.OperationParams = v
}

// SetOperationParams implements ydb generic interface for setting
// operation parameters inside driver implementation.
func (m *ExplainYqlRequest) SetOperationParams(v *Ydb_Operations.OperationParams) {
	m.OperationParams = v
}
