// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ydb_value.proto

package Ydb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type_PrimitiveTypeId int32

const (
	Type_PRIMITIVE_TYPE_ID_UNSPECIFIED Type_PrimitiveTypeId = 0
	Type_BOOL                          Type_PrimitiveTypeId = 6
	Type_INT8                          Type_PrimitiveTypeId = 7
	Type_UINT8                         Type_PrimitiveTypeId = 5
	Type_INT16                         Type_PrimitiveTypeId = 8
	Type_UINT16                        Type_PrimitiveTypeId = 9
	Type_INT32                         Type_PrimitiveTypeId = 1
	Type_UINT32                        Type_PrimitiveTypeId = 2
	Type_INT64                         Type_PrimitiveTypeId = 3
	Type_UINT64                        Type_PrimitiveTypeId = 4
	Type_FLOAT                         Type_PrimitiveTypeId = 33
	Type_DOUBLE                        Type_PrimitiveTypeId = 32
	Type_DATE                          Type_PrimitiveTypeId = 48
	Type_DATETIME                      Type_PrimitiveTypeId = 49
	Type_TIMESTAMP                     Type_PrimitiveTypeId = 50
	Type_INTERVAL                      Type_PrimitiveTypeId = 51
	Type_TZ_DATE                       Type_PrimitiveTypeId = 52
	Type_TZ_DATETIME                   Type_PrimitiveTypeId = 53
	Type_TZ_TIMESTAMP                  Type_PrimitiveTypeId = 54
	Type_STRING                        Type_PrimitiveTypeId = 4097
	Type_UTF8                          Type_PrimitiveTypeId = 4608
	Type_YSON                          Type_PrimitiveTypeId = 4609
	Type_JSON                          Type_PrimitiveTypeId = 4610
	Type_UUID                          Type_PrimitiveTypeId = 4611
)

var Type_PrimitiveTypeId_name = map[int32]string{
	0:    "PRIMITIVE_TYPE_ID_UNSPECIFIED",
	6:    "BOOL",
	7:    "INT8",
	5:    "UINT8",
	8:    "INT16",
	9:    "UINT16",
	1:    "INT32",
	2:    "UINT32",
	3:    "INT64",
	4:    "UINT64",
	33:   "FLOAT",
	32:   "DOUBLE",
	48:   "DATE",
	49:   "DATETIME",
	50:   "TIMESTAMP",
	51:   "INTERVAL",
	52:   "TZ_DATE",
	53:   "TZ_DATETIME",
	54:   "TZ_TIMESTAMP",
	4097: "STRING",
	4608: "UTF8",
	4609: "YSON",
	4610: "JSON",
	4611: "UUID",
}

var Type_PrimitiveTypeId_value = map[string]int32{
	"PRIMITIVE_TYPE_ID_UNSPECIFIED": 0,
	"BOOL":                          6,
	"INT8":                          7,
	"UINT8":                         5,
	"INT16":                         8,
	"UINT16":                        9,
	"INT32":                         1,
	"UINT32":                        2,
	"INT64":                         3,
	"UINT64":                        4,
	"FLOAT":                         33,
	"DOUBLE":                        32,
	"DATE":                          48,
	"DATETIME":                      49,
	"TIMESTAMP":                     50,
	"INTERVAL":                      51,
	"TZ_DATE":                       52,
	"TZ_DATETIME":                   53,
	"TZ_TIMESTAMP":                  54,
	"STRING":                        4097,
	"UTF8":                          4608,
	"YSON":                          4609,
	"JSON":                          4610,
	"UUID":                          4611,
}

func (x Type_PrimitiveTypeId) String() string {
	return proto.EnumName(Type_PrimitiveTypeId_name, int32(x))
}

func (Type_PrimitiveTypeId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{8, 0}
}

type DecimalType struct {
	Precision            uint32   `protobuf:"varint,1,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale                uint32   `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecimalType) Reset()         { *m = DecimalType{} }
func (m *DecimalType) String() string { return proto.CompactTextString(m) }
func (*DecimalType) ProtoMessage()    {}
func (*DecimalType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{0}
}

func (m *DecimalType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecimalType.Unmarshal(m, b)
}
func (m *DecimalType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecimalType.Marshal(b, m, deterministic)
}
func (m *DecimalType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecimalType.Merge(m, src)
}
func (m *DecimalType) XXX_Size() int {
	return xxx_messageInfo_DecimalType.Size(m)
}
func (m *DecimalType) XXX_DiscardUnknown() {
	xxx_messageInfo_DecimalType.DiscardUnknown(m)
}

var xxx_messageInfo_DecimalType proto.InternalMessageInfo

func (m *DecimalType) GetPrecision() uint32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *DecimalType) GetScale() uint32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

type OptionalType struct {
	Item                 *Type    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionalType) Reset()         { *m = OptionalType{} }
func (m *OptionalType) String() string { return proto.CompactTextString(m) }
func (*OptionalType) ProtoMessage()    {}
func (*OptionalType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{1}
}

func (m *OptionalType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionalType.Unmarshal(m, b)
}
func (m *OptionalType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionalType.Marshal(b, m, deterministic)
}
func (m *OptionalType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionalType.Merge(m, src)
}
func (m *OptionalType) XXX_Size() int {
	return xxx_messageInfo_OptionalType.Size(m)
}
func (m *OptionalType) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionalType.DiscardUnknown(m)
}

var xxx_messageInfo_OptionalType proto.InternalMessageInfo

func (m *OptionalType) GetItem() *Type {
	if m != nil {
		return m.Item
	}
	return nil
}

type ListType struct {
	Item                 *Type    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListType) Reset()         { *m = ListType{} }
func (m *ListType) String() string { return proto.CompactTextString(m) }
func (*ListType) ProtoMessage()    {}
func (*ListType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{2}
}

func (m *ListType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListType.Unmarshal(m, b)
}
func (m *ListType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListType.Marshal(b, m, deterministic)
}
func (m *ListType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListType.Merge(m, src)
}
func (m *ListType) XXX_Size() int {
	return xxx_messageInfo_ListType.Size(m)
}
func (m *ListType) XXX_DiscardUnknown() {
	xxx_messageInfo_ListType.DiscardUnknown(m)
}

var xxx_messageInfo_ListType proto.InternalMessageInfo

func (m *ListType) GetItem() *Type {
	if m != nil {
		return m.Item
	}
	return nil
}

type VariantType struct {
	// Types that are valid to be assigned to Type:
	//	*VariantType_TupleItems
	//	*VariantType_StructItems
	Type                 isVariantType_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VariantType) Reset()         { *m = VariantType{} }
func (m *VariantType) String() string { return proto.CompactTextString(m) }
func (*VariantType) ProtoMessage()    {}
func (*VariantType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{3}
}

func (m *VariantType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariantType.Unmarshal(m, b)
}
func (m *VariantType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariantType.Marshal(b, m, deterministic)
}
func (m *VariantType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariantType.Merge(m, src)
}
func (m *VariantType) XXX_Size() int {
	return xxx_messageInfo_VariantType.Size(m)
}
func (m *VariantType) XXX_DiscardUnknown() {
	xxx_messageInfo_VariantType.DiscardUnknown(m)
}

var xxx_messageInfo_VariantType proto.InternalMessageInfo

type isVariantType_Type interface {
	isVariantType_Type()
}

type VariantType_TupleItems struct {
	TupleItems *TupleType `protobuf:"bytes,1,opt,name=tuple_items,json=tupleItems,proto3,oneof"`
}

type VariantType_StructItems struct {
	StructItems *StructType `protobuf:"bytes,2,opt,name=struct_items,json=structItems,proto3,oneof"`
}

func (*VariantType_TupleItems) isVariantType_Type() {}

func (*VariantType_StructItems) isVariantType_Type() {}

func (m *VariantType) GetType() isVariantType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *VariantType) GetTupleItems() *TupleType {
	if x, ok := m.GetType().(*VariantType_TupleItems); ok {
		return x.TupleItems
	}
	return nil
}

func (m *VariantType) GetStructItems() *StructType {
	if x, ok := m.GetType().(*VariantType_StructItems); ok {
		return x.StructItems
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*VariantType) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _VariantType_OneofMarshaler, _VariantType_OneofUnmarshaler, _VariantType_OneofSizer, []interface{}{
		(*VariantType_TupleItems)(nil),
		(*VariantType_StructItems)(nil),
	}
}

func _VariantType_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*VariantType)
	// type
	switch x := m.Type.(type) {
	case *VariantType_TupleItems:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TupleItems); err != nil {
			return err
		}
	case *VariantType_StructItems:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StructItems); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("VariantType.Type has unexpected type %T", x)
	}
	return nil
}

func _VariantType_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*VariantType)
	switch tag {
	case 1: // type.tuple_items
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TupleType)
		err := b.DecodeMessage(msg)
		m.Type = &VariantType_TupleItems{msg}
		return true, err
	case 2: // type.struct_items
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StructType)
		err := b.DecodeMessage(msg)
		m.Type = &VariantType_StructItems{msg}
		return true, err
	default:
		return false, nil
	}
}

func _VariantType_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*VariantType)
	// type
	switch x := m.Type.(type) {
	case *VariantType_TupleItems:
		s := proto.Size(x.TupleItems)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *VariantType_StructItems:
		s := proto.Size(x.StructItems)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TupleType struct {
	Elements             []*Type  `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TupleType) Reset()         { *m = TupleType{} }
func (m *TupleType) String() string { return proto.CompactTextString(m) }
func (*TupleType) ProtoMessage()    {}
func (*TupleType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{4}
}

func (m *TupleType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TupleType.Unmarshal(m, b)
}
func (m *TupleType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TupleType.Marshal(b, m, deterministic)
}
func (m *TupleType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TupleType.Merge(m, src)
}
func (m *TupleType) XXX_Size() int {
	return xxx_messageInfo_TupleType.Size(m)
}
func (m *TupleType) XXX_DiscardUnknown() {
	xxx_messageInfo_TupleType.DiscardUnknown(m)
}

var xxx_messageInfo_TupleType proto.InternalMessageInfo

func (m *TupleType) GetElements() []*Type {
	if m != nil {
		return m.Elements
	}
	return nil
}

type StructMember struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 *Type    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructMember) Reset()         { *m = StructMember{} }
func (m *StructMember) String() string { return proto.CompactTextString(m) }
func (*StructMember) ProtoMessage()    {}
func (*StructMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{5}
}

func (m *StructMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructMember.Unmarshal(m, b)
}
func (m *StructMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructMember.Marshal(b, m, deterministic)
}
func (m *StructMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructMember.Merge(m, src)
}
func (m *StructMember) XXX_Size() int {
	return xxx_messageInfo_StructMember.Size(m)
}
func (m *StructMember) XXX_DiscardUnknown() {
	xxx_messageInfo_StructMember.DiscardUnknown(m)
}

var xxx_messageInfo_StructMember proto.InternalMessageInfo

func (m *StructMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StructMember) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

type StructType struct {
	Members              []*StructMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StructType) Reset()         { *m = StructType{} }
func (m *StructType) String() string { return proto.CompactTextString(m) }
func (*StructType) ProtoMessage()    {}
func (*StructType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{6}
}

func (m *StructType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructType.Unmarshal(m, b)
}
func (m *StructType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructType.Marshal(b, m, deterministic)
}
func (m *StructType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructType.Merge(m, src)
}
func (m *StructType) XXX_Size() int {
	return xxx_messageInfo_StructType.Size(m)
}
func (m *StructType) XXX_DiscardUnknown() {
	xxx_messageInfo_StructType.DiscardUnknown(m)
}

var xxx_messageInfo_StructType proto.InternalMessageInfo

func (m *StructType) GetMembers() []*StructMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type DictType struct {
	Key                  *Type    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Payload              *Type    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictType) Reset()         { *m = DictType{} }
func (m *DictType) String() string { return proto.CompactTextString(m) }
func (*DictType) ProtoMessage()    {}
func (*DictType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{7}
}

func (m *DictType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictType.Unmarshal(m, b)
}
func (m *DictType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictType.Marshal(b, m, deterministic)
}
func (m *DictType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictType.Merge(m, src)
}
func (m *DictType) XXX_Size() int {
	return xxx_messageInfo_DictType.Size(m)
}
func (m *DictType) XXX_DiscardUnknown() {
	xxx_messageInfo_DictType.DiscardUnknown(m)
}

var xxx_messageInfo_DictType proto.InternalMessageInfo

func (m *DictType) GetKey() *Type {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DictType) GetPayload() *Type {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Type struct {
	// Types that are valid to be assigned to Type:
	//	*Type_TypeId
	//	*Type_DecimalType
	//	*Type_OptionalType
	//	*Type_ListType
	//	*Type_TupleType
	//	*Type_StructType
	//	*Type_DictType
	//	*Type_VariantType
	//	*Type_VoidType
	Type                 isType_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{8}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

type isType_Type interface {
	isType_Type()
}

type Type_TypeId struct {
	TypeId Type_PrimitiveTypeId `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3,enum=Ydb.Type_PrimitiveTypeId,oneof"`
}

type Type_DecimalType struct {
	DecimalType *DecimalType `protobuf:"bytes,2,opt,name=decimal_type,json=decimalType,proto3,oneof"`
}

type Type_OptionalType struct {
	OptionalType *OptionalType `protobuf:"bytes,101,opt,name=optional_type,json=optionalType,proto3,oneof"`
}

type Type_ListType struct {
	ListType *ListType `protobuf:"bytes,102,opt,name=list_type,json=listType,proto3,oneof"`
}

type Type_TupleType struct {
	TupleType *TupleType `protobuf:"bytes,103,opt,name=tuple_type,json=tupleType,proto3,oneof"`
}

type Type_StructType struct {
	StructType *StructType `protobuf:"bytes,104,opt,name=struct_type,json=structType,proto3,oneof"`
}

type Type_DictType struct {
	DictType *DictType `protobuf:"bytes,105,opt,name=dict_type,json=dictType,proto3,oneof"`
}

type Type_VariantType struct {
	VariantType *VariantType `protobuf:"bytes,106,opt,name=variant_type,json=variantType,proto3,oneof"`
}

type Type_VoidType struct {
	VoidType _struct.NullValue `protobuf:"varint,201,opt,name=void_type,json=voidType,proto3,enum=google.protobuf.NullValue,oneof"`
}

func (*Type_TypeId) isType_Type() {}

func (*Type_DecimalType) isType_Type() {}

func (*Type_OptionalType) isType_Type() {}

func (*Type_ListType) isType_Type() {}

func (*Type_TupleType) isType_Type() {}

func (*Type_StructType) isType_Type() {}

func (*Type_DictType) isType_Type() {}

func (*Type_VariantType) isType_Type() {}

func (*Type_VoidType) isType_Type() {}

func (m *Type) GetType() isType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Type) GetTypeId() Type_PrimitiveTypeId {
	if x, ok := m.GetType().(*Type_TypeId); ok {
		return x.TypeId
	}
	return Type_PRIMITIVE_TYPE_ID_UNSPECIFIED
}

func (m *Type) GetDecimalType() *DecimalType {
	if x, ok := m.GetType().(*Type_DecimalType); ok {
		return x.DecimalType
	}
	return nil
}

func (m *Type) GetOptionalType() *OptionalType {
	if x, ok := m.GetType().(*Type_OptionalType); ok {
		return x.OptionalType
	}
	return nil
}

func (m *Type) GetListType() *ListType {
	if x, ok := m.GetType().(*Type_ListType); ok {
		return x.ListType
	}
	return nil
}

func (m *Type) GetTupleType() *TupleType {
	if x, ok := m.GetType().(*Type_TupleType); ok {
		return x.TupleType
	}
	return nil
}

func (m *Type) GetStructType() *StructType {
	if x, ok := m.GetType().(*Type_StructType); ok {
		return x.StructType
	}
	return nil
}

func (m *Type) GetDictType() *DictType {
	if x, ok := m.GetType().(*Type_DictType); ok {
		return x.DictType
	}
	return nil
}

func (m *Type) GetVariantType() *VariantType {
	if x, ok := m.GetType().(*Type_VariantType); ok {
		return x.VariantType
	}
	return nil
}

func (m *Type) GetVoidType() _struct.NullValue {
	if x, ok := m.GetType().(*Type_VoidType); ok {
		return x.VoidType
	}
	return _struct.NullValue_NULL_VALUE
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Type) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Type_OneofMarshaler, _Type_OneofUnmarshaler, _Type_OneofSizer, []interface{}{
		(*Type_TypeId)(nil),
		(*Type_DecimalType)(nil),
		(*Type_OptionalType)(nil),
		(*Type_ListType)(nil),
		(*Type_TupleType)(nil),
		(*Type_StructType)(nil),
		(*Type_DictType)(nil),
		(*Type_VariantType)(nil),
		(*Type_VoidType)(nil),
	}
}

func _Type_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Type)
	// type
	switch x := m.Type.(type) {
	case *Type_TypeId:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.TypeId))
	case *Type_DecimalType:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DecimalType); err != nil {
			return err
		}
	case *Type_OptionalType:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OptionalType); err != nil {
			return err
		}
	case *Type_ListType:
		b.EncodeVarint(102<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListType); err != nil {
			return err
		}
	case *Type_TupleType:
		b.EncodeVarint(103<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TupleType); err != nil {
			return err
		}
	case *Type_StructType:
		b.EncodeVarint(104<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StructType); err != nil {
			return err
		}
	case *Type_DictType:
		b.EncodeVarint(105<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DictType); err != nil {
			return err
		}
	case *Type_VariantType:
		b.EncodeVarint(106<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.VariantType); err != nil {
			return err
		}
	case *Type_VoidType:
		b.EncodeVarint(201<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VoidType))
	case nil:
	default:
		return fmt.Errorf("Type.Type has unexpected type %T", x)
	}
	return nil
}

func _Type_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Type)
	switch tag {
	case 1: // type.type_id
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Type = &Type_TypeId{Type_PrimitiveTypeId(x)}
		return true, err
	case 2: // type.decimal_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DecimalType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_DecimalType{msg}
		return true, err
	case 101: // type.optional_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OptionalType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_OptionalType{msg}
		return true, err
	case 102: // type.list_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_ListType{msg}
		return true, err
	case 103: // type.tuple_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TupleType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_TupleType{msg}
		return true, err
	case 104: // type.struct_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StructType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_StructType{msg}
		return true, err
	case 105: // type.dict_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DictType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_DictType{msg}
		return true, err
	case 106: // type.variant_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(VariantType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_VariantType{msg}
		return true, err
	case 201: // type.void_type
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Type = &Type_VoidType{_struct.NullValue(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Type_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Type)
	// type
	switch x := m.Type.(type) {
	case *Type_TypeId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.TypeId))
	case *Type_DecimalType:
		s := proto.Size(x.DecimalType)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_OptionalType:
		s := proto.Size(x.OptionalType)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_ListType:
		s := proto.Size(x.ListType)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_TupleType:
		s := proto.Size(x.TupleType)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_StructType:
		s := proto.Size(x.StructType)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_DictType:
		s := proto.Size(x.DictType)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_VariantType:
		s := proto.Size(x.VariantType)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_VoidType:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(x.VoidType))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ValuePair struct {
	Key                  *Value   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Payload              *Value   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValuePair) Reset()         { *m = ValuePair{} }
func (m *ValuePair) String() string { return proto.CompactTextString(m) }
func (*ValuePair) ProtoMessage()    {}
func (*ValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{9}
}

func (m *ValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValuePair.Unmarshal(m, b)
}
func (m *ValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValuePair.Marshal(b, m, deterministic)
}
func (m *ValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuePair.Merge(m, src)
}
func (m *ValuePair) XXX_Size() int {
	return xxx_messageInfo_ValuePair.Size(m)
}
func (m *ValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_ValuePair proto.InternalMessageInfo

func (m *ValuePair) GetKey() *Value {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ValuePair) GetPayload() *Value {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_BoolValue
	//	*Value_Int32Value
	//	*Value_Uint32Value
	//	*Value_Int64Value
	//	*Value_Uint64Value
	//	*Value_FloatValue
	//	*Value_DoubleValue
	//	*Value_BytesValue
	//	*Value_TextValue
	//	*Value_NullFlagValue
	//	*Value_NestedValue
	//	*Value_Low_128
	Value                isValue_Value `protobuf_oneof:"value"`
	Items                []*Value      `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	Pairs                []*ValuePair  `protobuf:"bytes,13,rep,name=pairs,proto3" json:"pairs,omitempty"`
	VariantIndex         uint32        `protobuf:"varint,14,opt,name=variant_index,json=variantIndex,proto3" json:"variant_index,omitempty"`
	High_128             uint64        `protobuf:"fixed64,16,opt,name=high_128,json=high128,proto3" json:"high_128,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{10}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_Int32Value struct {
	Int32Value int32 `protobuf:"fixed32,2,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Value_Uint32Value struct {
	Uint32Value uint32 `protobuf:"fixed32,3,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"fixed64,4,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_Uint64Value struct {
	Uint64Value uint64 `protobuf:"fixed64,5,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Value_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,7,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,8,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_TextValue struct {
	TextValue string `protobuf:"bytes,9,opt,name=text_value,json=textValue,proto3,oneof"`
}

type Value_NullFlagValue struct {
	NullFlagValue _struct.NullValue `protobuf:"varint,10,opt,name=null_flag_value,json=nullFlagValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

type Value_NestedValue struct {
	NestedValue *Value `protobuf:"bytes,11,opt,name=nested_value,json=nestedValue,proto3,oneof"`
}

type Value_Low_128 struct {
	Low_128 uint64 `protobuf:"fixed64,15,opt,name=low_128,json=low128,proto3,oneof"`
}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_Int32Value) isValue_Value() {}

func (*Value_Uint32Value) isValue_Value() {}

func (*Value_Int64Value) isValue_Value() {}

func (*Value_Uint64Value) isValue_Value() {}

func (*Value_FloatValue) isValue_Value() {}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_BytesValue) isValue_Value() {}

func (*Value_TextValue) isValue_Value() {}

func (*Value_NullFlagValue) isValue_Value() {}

func (*Value_NestedValue) isValue_Value() {}

func (*Value_Low_128) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetBoolValue() bool {
	if x, ok := m.GetValue().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *Value) GetInt32Value() int32 {
	if x, ok := m.GetValue().(*Value_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *Value) GetUint32Value() uint32 {
	if x, ok := m.GetValue().(*Value_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (m *Value) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*Value_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *Value) GetUint64Value() uint64 {
	if x, ok := m.GetValue().(*Value_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (m *Value) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Value_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Value) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Value) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*Value_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *Value) GetTextValue() string {
	if x, ok := m.GetValue().(*Value_TextValue); ok {
		return x.TextValue
	}
	return ""
}

func (m *Value) GetNullFlagValue() _struct.NullValue {
	if x, ok := m.GetValue().(*Value_NullFlagValue); ok {
		return x.NullFlagValue
	}
	return _struct.NullValue_NULL_VALUE
}

func (m *Value) GetNestedValue() *Value {
	if x, ok := m.GetValue().(*Value_NestedValue); ok {
		return x.NestedValue
	}
	return nil
}

func (m *Value) GetLow_128() uint64 {
	if x, ok := m.GetValue().(*Value_Low_128); ok {
		return x.Low_128
	}
	return 0
}

func (m *Value) GetItems() []*Value {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Value) GetPairs() []*ValuePair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *Value) GetVariantIndex() uint32 {
	if m != nil {
		return m.VariantIndex
	}
	return 0
}

func (m *Value) GetHigh_128() uint64 {
	if m != nil {
		return m.High_128
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_BoolValue)(nil),
		(*Value_Int32Value)(nil),
		(*Value_Uint32Value)(nil),
		(*Value_Int64Value)(nil),
		(*Value_Uint64Value)(nil),
		(*Value_FloatValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_TextValue)(nil),
		(*Value_NullFlagValue)(nil),
		(*Value_NestedValue)(nil),
		(*Value_Low_128)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_BoolValue:
		t := uint64(0)
		if x.BoolValue {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Value_Int32Value:
		b.EncodeVarint(2<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(x.Int32Value))
	case *Value_Uint32Value:
		b.EncodeVarint(3<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(x.Uint32Value))
	case *Value_Int64Value:
		b.EncodeVarint(4<<3 | proto.WireFixed64)
		b.EncodeFixed64(uint64(x.Int64Value))
	case *Value_Uint64Value:
		b.EncodeVarint(5<<3 | proto.WireFixed64)
		b.EncodeFixed64(uint64(x.Uint64Value))
	case *Value_FloatValue:
		b.EncodeVarint(6<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.FloatValue)))
	case *Value_DoubleValue:
		b.EncodeVarint(7<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *Value_BytesValue:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.BytesValue)
	case *Value_TextValue:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.TextValue)
	case *Value_NullFlagValue:
		b.EncodeVarint(10<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.NullFlagValue))
	case *Value_NestedValue:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NestedValue); err != nil {
			return err
		}
	case *Value_Low_128:
		b.EncodeVarint(15<<3 | proto.WireFixed64)
		b.EncodeFixed64(uint64(x.Low_128))
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // value.bool_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_BoolValue{x != 0}
		return true, err
	case 2: // value.int32_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Value_Int32Value{int32(x)}
		return true, err
	case 3: // value.uint32_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Value_Uint32Value{uint32(x)}
		return true, err
	case 4: // value.int64_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Value_Int64Value{int64(x)}
		return true, err
	case 5: // value.uint64_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Value_Uint64Value{x}
		return true, err
	case 6: // value.float_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Value_FloatValue{math.Float32frombits(uint32(x))}
		return true, err
	case 7: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Value_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 8: // value.bytes_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &Value_BytesValue{x}
		return true, err
	case 9: // value.text_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Value_TextValue{x}
		return true, err
	case 10: // value.null_flag_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_NullFlagValue{_struct.NullValue(x)}
		return true, err
	case 11: // value.nested_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Value)
		err := b.DecodeMessage(msg)
		m.Value = &Value_NestedValue{msg}
		return true, err
	case 15: // value.low_128
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Value_Low_128{x}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_BoolValue:
		n += 1 // tag and wire
		n += 1
	case *Value_Int32Value:
		n += 1 // tag and wire
		n += 4
	case *Value_Uint32Value:
		n += 1 // tag and wire
		n += 4
	case *Value_Int64Value:
		n += 1 // tag and wire
		n += 8
	case *Value_Uint64Value:
		n += 1 // tag and wire
		n += 8
	case *Value_FloatValue:
		n += 1 // tag and wire
		n += 4
	case *Value_DoubleValue:
		n += 1 // tag and wire
		n += 8
	case *Value_BytesValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.BytesValue)))
		n += len(x.BytesValue)
	case *Value_TextValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.TextValue)))
		n += len(x.TextValue)
	case *Value_NullFlagValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.NullFlagValue))
	case *Value_NestedValue:
		s := proto.Size(x.NestedValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_Low_128:
		n += 1 // tag and wire
		n += 8
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TypedValue struct {
	Type                 *Type    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                *Value   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypedValue) Reset()         { *m = TypedValue{} }
func (m *TypedValue) String() string { return proto.CompactTextString(m) }
func (*TypedValue) ProtoMessage()    {}
func (*TypedValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{11}
}

func (m *TypedValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypedValue.Unmarshal(m, b)
}
func (m *TypedValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypedValue.Marshal(b, m, deterministic)
}
func (m *TypedValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypedValue.Merge(m, src)
}
func (m *TypedValue) XXX_Size() int {
	return xxx_messageInfo_TypedValue.Size(m)
}
func (m *TypedValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TypedValue.DiscardUnknown(m)
}

var xxx_messageInfo_TypedValue proto.InternalMessageInfo

func (m *TypedValue) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TypedValue) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Column struct {
	// Name of column
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of column
	Type                 *Type    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{12}
}

func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Column) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

// Represents table-like structure with ordered set of rows and columns
type ResultSet struct {
	// Metadata of columns
	Columns []*Column `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	// Rows of table
	Rows []*Value `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	// Flag indicates the result was truncated
	Truncated            bool     `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultSet) Reset()         { *m = ResultSet{} }
func (m *ResultSet) String() string { return proto.CompactTextString(m) }
func (*ResultSet) ProtoMessage()    {}
func (*ResultSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06b6eea133728f3, []int{13}
}

func (m *ResultSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultSet.Unmarshal(m, b)
}
func (m *ResultSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultSet.Marshal(b, m, deterministic)
}
func (m *ResultSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultSet.Merge(m, src)
}
func (m *ResultSet) XXX_Size() int {
	return xxx_messageInfo_ResultSet.Size(m)
}
func (m *ResultSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultSet.DiscardUnknown(m)
}

var xxx_messageInfo_ResultSet proto.InternalMessageInfo

func (m *ResultSet) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *ResultSet) GetRows() []*Value {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *ResultSet) GetTruncated() bool {
	if m != nil {
		return m.Truncated
	}
	return false
}

func init() {
	proto.RegisterEnum("Ydb.Type_PrimitiveTypeId", Type_PrimitiveTypeId_name, Type_PrimitiveTypeId_value)
	proto.RegisterType((*DecimalType)(nil), "Ydb.DecimalType")
	proto.RegisterType((*OptionalType)(nil), "Ydb.OptionalType")
	proto.RegisterType((*ListType)(nil), "Ydb.ListType")
	proto.RegisterType((*VariantType)(nil), "Ydb.VariantType")
	proto.RegisterType((*TupleType)(nil), "Ydb.TupleType")
	proto.RegisterType((*StructMember)(nil), "Ydb.StructMember")
	proto.RegisterType((*StructType)(nil), "Ydb.StructType")
	proto.RegisterType((*DictType)(nil), "Ydb.DictType")
	proto.RegisterType((*Type)(nil), "Ydb.Type")
	proto.RegisterType((*ValuePair)(nil), "Ydb.ValuePair")
	proto.RegisterType((*Value)(nil), "Ydb.Value")
	proto.RegisterType((*TypedValue)(nil), "Ydb.TypedValue")
	proto.RegisterType((*Column)(nil), "Ydb.Column")
	proto.RegisterType((*ResultSet)(nil), "Ydb.ResultSet")
}

func init() { proto.RegisterFile("ydb_value.proto", fileDescriptor_c06b6eea133728f3) }

var fileDescriptor_c06b6eea133728f3 = []byte{
	// 1159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdf, 0x72, 0xda, 0xc6,
	0x17, 0xb6, 0x6c, 0xfe, 0xe9, 0x48, 0x18, 0xfd, 0x76, 0x7e, 0x17, 0x4e, 0x9a, 0x34, 0x98, 0x38,
	0x33, 0x74, 0x9a, 0xe2, 0x82, 0x09, 0x43, 0xdb, 0x2b, 0x08, 0xb8, 0x56, 0x07, 0x03, 0x23, 0x84,
	0x67, 0x9c, 0x1b, 0x46, 0xa0, 0x35, 0x51, 0xbb, 0x20, 0x06, 0x49, 0xb6, 0xb9, 0xe9, 0x34, 0xed,
	0x53, 0xf5, 0x11, 0x7a, 0xd1, 0xe7, 0xe8, 0x2b, 0xf4, 0xb2, 0x73, 0x76, 0x57, 0xa0, 0x38, 0xcd,
	0x4c, 0xa6, 0x77, 0x87, 0xb3, 0xdf, 0xf7, 0xed, 0xd1, 0xd9, 0xef, 0xec, 0x02, 0x85, 0x8d, 0x3b,
	0x9d, 0xdc, 0x3a, 0x2c, 0xa2, 0x95, 0xd5, 0xda, 0x0f, 0x7d, 0x72, 0x70, 0xed, 0x4e, 0x1f, 0x3f,
	0x99, 0xfb, 0xfe, 0x9c, 0xd1, 0x53, 0x9e, 0x9a, 0x46, 0x37, 0xa7, 0x41, 0xb8, 0x8e, 0x66, 0xa1,
	0x80, 0x94, 0x5a, 0xa0, 0x75, 0xe8, 0xcc, 0x5b, 0x38, 0xcc, 0xde, 0xac, 0x28, 0x79, 0x02, 0xea,
	0x6a, 0x4d, 0x67, 0x5e, 0xe0, 0xf9, 0xcb, 0x23, 0xa5, 0xa8, 0x94, 0xf3, 0xd6, 0x2e, 0x41, 0xfe,
	0x0f, 0xe9, 0x60, 0xe6, 0x30, 0x7a, 0xb4, 0xcf, 0x57, 0xc4, 0x8f, 0xd2, 0x57, 0xa0, 0x0f, 0x56,
	0xa1, 0xe7, 0x2f, 0xa5, 0xc6, 0x53, 0x48, 0x79, 0x21, 0x5d, 0x70, 0xba, 0x56, 0x53, 0x2b, 0xd7,
	0xee, 0xb4, 0x82, 0x0b, 0x16, 0x4f, 0x97, 0xbe, 0x80, 0x5c, 0xcf, 0x0b, 0xc2, 0x4f, 0x81, 0xfe,
	0x0c, 0xda, 0x95, 0xb3, 0xf6, 0x9c, 0xa5, 0x40, 0x57, 0x41, 0x0b, 0xa3, 0x15, 0xa3, 0x13, 0x5c,
	0x0c, 0x24, 0xe9, 0x50, 0x90, 0x30, 0x8f, 0xa0, 0x8b, 0x3d, 0x0b, 0x38, 0xc8, 0x44, 0x0c, 0xa9,
	0x83, 0x2e, 0x3e, 0x57, 0x72, 0xf6, 0x39, 0xa7, 0xc0, 0x39, 0x23, 0xbe, 0x20, 0x49, 0x9a, 0x80,
	0x71, 0x56, 0x3b, 0x03, 0xa9, 0x70, 0xb3, 0xa2, 0xa5, 0x1a, 0xa8, 0x5b, 0x61, 0xf2, 0x02, 0x72,
	0x94, 0xd1, 0x05, 0x5d, 0x86, 0xb8, 0xf5, 0xc1, 0xfb, 0xf5, 0x6e, 0x97, 0x4a, 0x2d, 0xd0, 0x85,
	0xf0, 0x25, 0x5d, 0x4c, 0xe9, 0x9a, 0x10, 0x48, 0x2d, 0x9d, 0x05, 0xe5, 0xd5, 0xaa, 0x16, 0x8f,
	0xf1, 0xb3, 0x51, 0x5f, 0x56, 0x93, 0xfc, 0x6c, 0xbe, 0xed, 0x37, 0x00, 0xbb, 0xda, 0xc8, 0x97,
	0x90, 0x5d, 0x70, 0xa9, 0x78, 0xdb, 0xff, 0x25, 0xaa, 0x17, 0x9b, 0x58, 0x31, 0xa2, 0xd4, 0x83,
	0x5c, 0xc7, 0x93, 0xc4, 0xcf, 0xe0, 0xe0, 0x27, 0xba, 0xf9, 0xb0, 0xb7, 0x98, 0x25, 0xcf, 0x21,
	0xbb, 0x72, 0x36, 0xcc, 0x77, 0xdc, 0x0f, 0xab, 0x88, 0x57, 0x4a, 0xbf, 0x67, 0x20, 0xc5, 0xa5,
	0xea, 0x90, 0xc5, 0xca, 0x26, 0x9e, 0xcb, 0xe5, 0x0e, 0x6b, 0x8f, 0xb6, 0xe8, 0xca, 0x70, 0xed,
	0x2d, 0xbc, 0xd0, 0xbb, 0xe5, 0x5d, 0x32, 0xdd, 0x8b, 0x3d, 0x2b, 0x13, 0xf2, 0x88, 0xbc, 0x02,
	0xdd, 0x15, 0xde, 0x9a, 0x24, 0x3e, 0xd7, 0xe0, 0xd4, 0x84, 0xe9, 0xb0, 0xfb, 0x6e, 0xc2, 0x83,
	0x4d, 0xc8, 0xfb, 0xd2, 0x4f, 0x82, 0x47, 0x39, 0x4f, 0x7c, 0x76, 0xd2, 0x69, 0x17, 0x7b, 0x96,
	0xee, 0x27, 0x9d, 0xf7, 0x12, 0x54, 0xe6, 0x05, 0xa1, 0x60, 0xdd, 0x70, 0x56, 0x9e, 0xb3, 0x62,
	0xc3, 0x5d, 0xec, 0x59, 0x39, 0x16, 0x9b, 0xef, 0x14, 0x84, 0x53, 0x04, 0x7c, 0xfe, 0x11, 0x37,
	0xa9, 0xe1, 0xd6, 0x01, 0x35, 0x90, 0x2e, 0x11, 0x8c, 0xb7, 0x1f, 0xf3, 0x12, 0x04, 0xbb, 0xd3,
	0x7b, 0x09, 0xaa, 0xeb, 0xc5, 0x0c, 0x2f, 0x51, 0x52, 0x7c, 0x4c, 0x58, 0x92, 0x1b, 0x1f, 0xd9,
	0x2b, 0xd0, 0x6f, 0x85, 0xe1, 0x05, 0xe1, 0xc7, 0x44, 0xc7, 0x12, 0x93, 0x80, 0x1d, 0xbb, 0x4d,
	0x0c, 0xc6, 0xb7, 0xa0, 0xde, 0xfa, 0x9e, 0x2b, 0x38, 0x7f, 0x88, 0x13, 0x7a, 0x5c, 0x11, 0x73,
	0x5f, 0x89, 0xe7, 0xbe, 0xd2, 0x8f, 0x18, 0xbb, 0xc2, 0xdb, 0x01, 0xb7, 0x44, 0x3c, 0x72, 0x4b,
	0x7f, 0xee, 0x43, 0xe1, 0xc1, 0x11, 0x92, 0x63, 0x78, 0x3a, 0xb4, 0xcc, 0x4b, 0xd3, 0x36, 0xaf,
	0xba, 0x13, 0xfb, 0x7a, 0xd8, 0x9d, 0x98, 0x9d, 0xc9, 0xb8, 0x3f, 0x1a, 0x76, 0x5f, 0x9b, 0xe7,
	0x66, 0xb7, 0x63, 0xec, 0x91, 0x1c, 0xa4, 0xda, 0x83, 0x41, 0xcf, 0xc8, 0x60, 0x64, 0xf6, 0xed,
	0xa6, 0x91, 0x25, 0x2a, 0xa4, 0xc7, 0x3c, 0x4c, 0x63, 0x68, 0xf6, 0xed, 0x6a, 0xc3, 0xc8, 0x11,
	0x80, 0xcc, 0x58, 0xc4, 0xaa, 0x4c, 0x9f, 0xd5, 0x0c, 0x25, 0x4e, 0x9f, 0xd5, 0x8c, 0x7d, 0x99,
	0x6e, 0xd4, 0x8d, 0x83, 0x38, 0xdd, 0xa8, 0x1b, 0x29, 0x4c, 0x9f, 0xf7, 0x06, 0x2d, 0xdb, 0x38,
	0xc6, 0x74, 0x67, 0x30, 0x6e, 0xf7, 0xba, 0x46, 0x11, 0x37, 0xec, 0xb4, 0xec, 0xae, 0xf1, 0x35,
	0xd1, 0x21, 0x87, 0x91, 0x6d, 0x5e, 0x76, 0x8d, 0x2a, 0xc9, 0x83, 0x8a, 0xd1, 0xc8, 0x6e, 0x5d,
	0x0e, 0x8d, 0x1a, 0x2e, 0x9a, 0x7d, 0xbb, 0x6b, 0x5d, 0xb5, 0x7a, 0xc6, 0x19, 0xd1, 0x20, 0x6b,
	0xbf, 0x99, 0x70, 0x5e, 0x9d, 0x14, 0x40, 0x93, 0x3f, 0x38, 0xf5, 0x15, 0x31, 0x40, 0xb7, 0xdf,
	0x4c, 0x76, 0xec, 0x06, 0xd1, 0x20, 0x33, 0xb2, 0x2d, 0xb3, 0xff, 0xbd, 0xf1, 0xae, 0x48, 0x54,
	0x48, 0x8d, 0xed, 0xf3, 0xa6, 0xf1, 0xcb, 0x09, 0x86, 0xd7, 0xa3, 0x41, 0xdf, 0x78, 0xc7, 0xc3,
	0x1f, 0x30, 0xfc, 0x95, 0x87, 0xe3, 0xb1, 0xd9, 0x31, 0x7e, 0x3b, 0xd9, 0xde, 0x1d, 0x03, 0x50,
	0x79, 0xb3, 0x87, 0x8e, 0xb7, 0x26, 0x4f, 0x92, 0xa3, 0x08, 0xf2, 0x38, 0x59, 0x24, 0x67, 0xf1,
	0xe4, 0xe1, 0x2c, 0x26, 0x11, 0xdb, 0x61, 0xfc, 0x2b, 0x05, 0x69, 0x9e, 0x22, 0xcf, 0x00, 0xa6,
	0xbe, 0xcf, 0xc4, 0x55, 0xcf, 0x45, 0x73, 0x68, 0x54, 0xcc, 0x09, 0xc0, 0x31, 0x68, 0xde, 0x32,
	0x3c, 0xab, 0x49, 0x04, 0x8a, 0x16, 0xd0, 0x97, 0x3c, 0x29, 0x20, 0xcf, 0x41, 0x8f, 0x92, 0x98,
	0x83, 0xa2, 0x52, 0xce, 0xa2, 0xaf, 0xa2, 0x04, 0x48, 0xe8, 0x34, 0xea, 0x12, 0x93, 0x2a, 0x2a,
	0x65, 0x43, 0xea, 0x34, 0xea, 0xef, 0xe9, 0x6c, 0x31, 0xe9, 0xa2, 0x52, 0xce, 0xc4, 0x3a, 0x31,
	0xe8, 0x18, 0xb4, 0x1b, 0xe6, 0x3b, 0xa1, 0xc4, 0x64, 0x8a, 0x4a, 0x79, 0x1f, 0x75, 0x78, 0x72,
	0xab, 0xe3, 0xfa, 0xd1, 0x94, 0x51, 0x89, 0xc9, 0x16, 0x95, 0xb2, 0xc2, 0x6f, 0x06, 0x9e, 0xdd,
	0xea, 0x4c, 0x37, 0x21, 0x0d, 0x24, 0x26, 0x57, 0x54, 0xca, 0x3a, 0xea, 0xf0, 0xe4, 0xb6, 0x37,
	0x21, 0xbd, 0x8f, 0x77, 0x52, 0xf1, 0xd2, 0xe5, 0x43, 0x4c, 0xef, 0xe5, 0x46, 0x1d, 0x28, 0x2c,
	0x23, 0xc6, 0x26, 0x37, 0xcc, 0x99, 0x4b, 0x14, 0x7c, 0xc2, 0xc0, 0xe4, 0x91, 0x74, 0xce, 0x9c,
	0xb9, 0x50, 0x39, 0x05, 0x7d, 0x49, 0x83, 0x90, 0xba, 0x52, 0x42, 0x7b, 0x78, 0x6e, 0x58, 0xba,
	0x40, 0x08, 0xc2, 0x23, 0xc8, 0x32, 0xff, 0x6e, 0x52, 0xad, 0x35, 0x8f, 0x0a, 0xb2, 0x45, 0x19,
	0xe6, 0xdf, 0x55, 0x6b, 0x4d, 0x52, 0x84, 0xb4, 0x78, 0x9c, 0x74, 0x7e, 0xbd, 0x27, 0x0f, 0x5f,
	0x2c, 0x90, 0x13, 0x48, 0xaf, 0x1c, 0x6f, 0x1d, 0x1c, 0xe5, 0x39, 0xe2, 0x70, 0x87, 0x40, 0x77,
	0x59, 0x62, 0x91, 0x3c, 0x87, 0x7c, 0x7c, 0x79, 0x78, 0x4b, 0x97, 0xde, 0x1f, 0x1d, 0xf2, 0x57,
	0x3a, 0xbe, 0x51, 0x4c, 0xcc, 0x91, 0x47, 0x90, 0x7b, 0xeb, 0xcd, 0xdf, 0xf2, 0x42, 0x0c, 0x2c,
	0xc4, 0xca, 0xe2, 0xef, 0x6a, 0xad, 0xd9, 0xce, 0x42, 0x9a, 0x7f, 0x4c, 0xe9, 0x12, 0x00, 0x2f,
	0x02, 0x59, 0x79, 0xfc, 0x58, 0x29, 0xff, 0xfa, 0x58, 0x61, 0xf5, 0x3b, 0x97, 0x3d, 0xa8, 0x5e,
	0xc8, 0x7d, 0x07, 0x99, 0xd7, 0x3e, 0x8b, 0x16, 0xcb, 0xff, 0xf2, 0x16, 0xae, 0x40, 0xb5, 0x68,
	0x10, 0xb1, 0x70, 0x44, 0x43, 0xf2, 0x02, 0xb2, 0x33, 0xae, 0x14, 0x3f, 0x85, 0x1a, 0x87, 0x0b,
	0x75, 0x2b, 0x5e, 0x23, 0x9f, 0x43, 0x6a, 0xed, 0xdf, 0xe1, 0x63, 0xff, 0xb0, 0x9f, 0x3c, 0x8f,
	0x7f, 0x72, 0xc2, 0x75, 0xb4, 0x9c, 0x39, 0x21, 0x75, 0xb9, 0xf1, 0x73, 0xd6, 0x2e, 0xd1, 0x7e,
	0x06, 0xf9, 0x75, 0x54, 0xd9, 0x38, 0xd8, 0xae, 0xca, 0xc6, 0x9d, 0xb6, 0x35, 0xd1, 0x69, 0x74,
	0x45, 0xf0, 0xb7, 0xa2, 0x4c, 0x33, 0xdc, 0x20, 0x67, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0x11, 0x68, 0x56, 0x6f, 0x09, 0x00, 0x00,
}

const ()
