// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ydb_operation.proto

package Ydb_Operations

import (
	Ydb "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb"
	Ydb_Issue "github.com/yandex-cloud/ydb-go-sdk/v2/api/protos/Ydb_Issue"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperationParams_OperationMode int32

const (
	OperationParams_OPERATION_MODE_UNSPECIFIED OperationParams_OperationMode = 0
	// Server will only reply once operation is finished (ready=true), and operation object won't be
	// accessible after the reply. This is a basic request-response mode.
	OperationParams_SYNC  OperationParams_OperationMode = 1
	OperationParams_ASYNC OperationParams_OperationMode = 2
)

var OperationParams_OperationMode_name = map[int32]string{
	0: "OPERATION_MODE_UNSPECIFIED",
	1: "SYNC",
	2: "ASYNC",
}

var OperationParams_OperationMode_value = map[string]int32{
	"OPERATION_MODE_UNSPECIFIED": 0,
	"SYNC":                       1,
	"ASYNC":                      2,
}

func (x OperationParams_OperationMode) String() string {
	return proto.EnumName(OperationParams_OperationMode_name, int32(x))
}

func (OperationParams_OperationMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{0, 0}
}

type OperationParams struct {
	OperationMode OperationParams_OperationMode `protobuf:"varint,1,opt,name=operation_mode,json=operationMode,proto3,enum=Ydb.Operations.OperationParams_OperationMode" json:"operation_mode,omitempty"`
	// Indicates that client is no longer interested in the result of operation after the specified duration
	// starting from the time operation arrives at the server.
	// Server will try to stop the execution of operation and if no result is currently available the operation
	// will receive TIMEOUT status code, which will be sent back to client if it was waiting for the operation result.
	// Timeout of operation does not tell anything about its result, it might be completed successfully
	// or cancelled on server.
	OperationTimeout *durationpb.Duration `protobuf:"bytes,2,opt,name=operation_timeout,json=operationTimeout,proto3" json:"operation_timeout,omitempty"`
	// Server will try to cancel the operation after the specified duration starting from the time
	// the operation arrives at server.
	// In case of successful cancellation operation will receive CANCELLED status code, which will be
	// sent back to client if it was waiting for the operation result.
	// In case when cancellation isn't possible, no action will be performed.
	CancelAfter *durationpb.Duration `protobuf:"bytes,3,opt,name=cancel_after,json=cancelAfter,proto3" json:"cancel_after,omitempty"`
	// User-defined labels of operation.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// If enabled, server will report cost information, if supported by the operation.
	// This flag is mostly useful for SYNC operations, to get the cost information in the response.
	ReportCostInfo       Ydb.FeatureFlag_Status `protobuf:"varint,5,opt,name=report_cost_info,json=reportCostInfo,proto3,enum=Ydb.FeatureFlag_Status" json:"report_cost_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OperationParams) Reset()         { *m = OperationParams{} }
func (m *OperationParams) String() string { return proto.CompactTextString(m) }
func (*OperationParams) ProtoMessage()    {}
func (*OperationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{0}
}

func (m *OperationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationParams.Unmarshal(m, b)
}
func (m *OperationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationParams.Marshal(b, m, deterministic)
}
func (m *OperationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationParams.Merge(m, src)
}
func (m *OperationParams) XXX_Size() int {
	return xxx_messageInfo_OperationParams.Size(m)
}
func (m *OperationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationParams.DiscardUnknown(m)
}

var xxx_messageInfo_OperationParams proto.InternalMessageInfo

func (m *OperationParams) GetOperationMode() OperationParams_OperationMode {
	if m != nil {
		return m.OperationMode
	}
	return OperationParams_OPERATION_MODE_UNSPECIFIED
}

func (m *OperationParams) GetOperationTimeout() *durationpb.Duration {
	if m != nil {
		return m.OperationTimeout
	}
	return nil
}

func (m *OperationParams) GetCancelAfter() *durationpb.Duration {
	if m != nil {
		return m.CancelAfter
	}
	return nil
}

func (m *OperationParams) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *OperationParams) GetReportCostInfo() Ydb.FeatureFlag_Status {
	if m != nil {
		return m.ReportCostInfo
	}
	return Ydb.FeatureFlag_STATUS_UNSPECIFIED
}

type GetOperationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOperationRequest) Reset()         { *m = GetOperationRequest{} }
func (m *GetOperationRequest) String() string { return proto.CompactTextString(m) }
func (*GetOperationRequest) ProtoMessage()    {}
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{1}
}

func (m *GetOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperationRequest.Unmarshal(m, b)
}
func (m *GetOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperationRequest.Marshal(b, m, deterministic)
}
func (m *GetOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperationRequest.Merge(m, src)
}
func (m *GetOperationRequest) XXX_Size() int {
	return xxx_messageInfo_GetOperationRequest.Size(m)
}
func (m *GetOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperationRequest proto.InternalMessageInfo

func (m *GetOperationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOperationResponse struct {
	Operation            *Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetOperationResponse) Reset()         { *m = GetOperationResponse{} }
func (m *GetOperationResponse) String() string { return proto.CompactTextString(m) }
func (*GetOperationResponse) ProtoMessage()    {}
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{2}
}

func (m *GetOperationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperationResponse.Unmarshal(m, b)
}
func (m *GetOperationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperationResponse.Marshal(b, m, deterministic)
}
func (m *GetOperationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperationResponse.Merge(m, src)
}
func (m *GetOperationResponse) XXX_Size() int {
	return xxx_messageInfo_GetOperationResponse.Size(m)
}
func (m *GetOperationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperationResponse proto.InternalMessageInfo

func (m *GetOperationResponse) GetOperation() *Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type CancelOperationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOperationRequest) Reset()         { *m = CancelOperationRequest{} }
func (m *CancelOperationRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOperationRequest) ProtoMessage()    {}
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{3}
}

func (m *CancelOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOperationRequest.Unmarshal(m, b)
}
func (m *CancelOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOperationRequest.Marshal(b, m, deterministic)
}
func (m *CancelOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOperationRequest.Merge(m, src)
}
func (m *CancelOperationRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOperationRequest.Size(m)
}
func (m *CancelOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOperationRequest proto.InternalMessageInfo

func (m *CancelOperationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CancelOperationResponse struct {
	Status               Ydb.StatusIds_StatusCode  `protobuf:"varint,1,opt,name=status,proto3,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues               []*Ydb_Issue.IssueMessage `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CancelOperationResponse) Reset()         { *m = CancelOperationResponse{} }
func (m *CancelOperationResponse) String() string { return proto.CompactTextString(m) }
func (*CancelOperationResponse) ProtoMessage()    {}
func (*CancelOperationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{4}
}

func (m *CancelOperationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOperationResponse.Unmarshal(m, b)
}
func (m *CancelOperationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOperationResponse.Marshal(b, m, deterministic)
}
func (m *CancelOperationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOperationResponse.Merge(m, src)
}
func (m *CancelOperationResponse) XXX_Size() int {
	return xxx_messageInfo_CancelOperationResponse.Size(m)
}
func (m *CancelOperationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOperationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOperationResponse proto.InternalMessageInfo

func (m *CancelOperationResponse) GetStatus() Ydb.StatusIds_StatusCode {
	if m != nil {
		return m.Status
	}
	return Ydb.StatusIds_STATUS_CODE_UNSPECIFIED
}

func (m *CancelOperationResponse) GetIssues() []*Ydb_Issue.IssueMessage {
	if m != nil {
		return m.Issues
	}
	return nil
}

type ForgetOperationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetOperationRequest) Reset()         { *m = ForgetOperationRequest{} }
func (m *ForgetOperationRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetOperationRequest) ProtoMessage()    {}
func (*ForgetOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{5}
}

func (m *ForgetOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetOperationRequest.Unmarshal(m, b)
}
func (m *ForgetOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetOperationRequest.Marshal(b, m, deterministic)
}
func (m *ForgetOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetOperationRequest.Merge(m, src)
}
func (m *ForgetOperationRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetOperationRequest.Size(m)
}
func (m *ForgetOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetOperationRequest proto.InternalMessageInfo

func (m *ForgetOperationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ForgetOperationResponse struct {
	Status               Ydb.StatusIds_StatusCode  `protobuf:"varint,1,opt,name=status,proto3,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues               []*Ydb_Issue.IssueMessage `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ForgetOperationResponse) Reset()         { *m = ForgetOperationResponse{} }
func (m *ForgetOperationResponse) String() string { return proto.CompactTextString(m) }
func (*ForgetOperationResponse) ProtoMessage()    {}
func (*ForgetOperationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{6}
}

func (m *ForgetOperationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetOperationResponse.Unmarshal(m, b)
}
func (m *ForgetOperationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetOperationResponse.Marshal(b, m, deterministic)
}
func (m *ForgetOperationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetOperationResponse.Merge(m, src)
}
func (m *ForgetOperationResponse) XXX_Size() int {
	return xxx_messageInfo_ForgetOperationResponse.Size(m)
}
func (m *ForgetOperationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetOperationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetOperationResponse proto.InternalMessageInfo

func (m *ForgetOperationResponse) GetStatus() Ydb.StatusIds_StatusCode {
	if m != nil {
		return m.Status
	}
	return Ydb.StatusIds_STATUS_CODE_UNSPECIFIED
}

func (m *ForgetOperationResponse) GetIssues() []*Ydb_Issue.IssueMessage {
	if m != nil {
		return m.Issues
	}
	return nil
}

type ListOperationsRequest struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	PageSize             uint64   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOperationsRequest) Reset()         { *m = ListOperationsRequest{} }
func (m *ListOperationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListOperationsRequest) ProtoMessage()    {}
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{7}
}

func (m *ListOperationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOperationsRequest.Unmarshal(m, b)
}
func (m *ListOperationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOperationsRequest.Marshal(b, m, deterministic)
}
func (m *ListOperationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOperationsRequest.Merge(m, src)
}
func (m *ListOperationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListOperationsRequest.Size(m)
}
func (m *ListOperationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOperationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOperationsRequest proto.InternalMessageInfo

func (m *ListOperationsRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ListOperationsRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOperationsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListOperationsResponse struct {
	Status               Ydb.StatusIds_StatusCode  `protobuf:"varint,1,opt,name=status,proto3,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues               []*Ydb_Issue.IssueMessage `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	Operations           []*Operation              `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"`
	NextPageToken        string                    `protobuf:"bytes,4,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListOperationsResponse) Reset()         { *m = ListOperationsResponse{} }
func (m *ListOperationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListOperationsResponse) ProtoMessage()    {}
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{8}
}

func (m *ListOperationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOperationsResponse.Unmarshal(m, b)
}
func (m *ListOperationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOperationsResponse.Marshal(b, m, deterministic)
}
func (m *ListOperationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOperationsResponse.Merge(m, src)
}
func (m *ListOperationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListOperationsResponse.Size(m)
}
func (m *ListOperationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOperationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOperationsResponse proto.InternalMessageInfo

func (m *ListOperationsResponse) GetStatus() Ydb.StatusIds_StatusCode {
	if m != nil {
		return m.Status
	}
	return Ydb.StatusIds_STATUS_CODE_UNSPECIFIED
}

func (m *ListOperationsResponse) GetIssues() []*Ydb_Issue.IssueMessage {
	if m != nil {
		return m.Issues
	}
	return nil
}

func (m *ListOperationsResponse) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *ListOperationsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type Operation struct {
	// Identifier of the operation, empty value means no active operation object is present (it was forgotten or
	// not created in the first place, as in SYNC operation mode).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// true - this operation has beed finished (doesn't matter successful or not),
	// so Status field has status code, and Result field can contains result data.
	// false - this operation still running. You can repeat request using operation Id.
	Ready  bool                      `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Status Ydb.StatusIds_StatusCode  `protobuf:"varint,3,opt,name=status,proto3,enum=Ydb.StatusIds_StatusCode" json:"status,omitempty"`
	Issues []*Ydb_Issue.IssueMessage `protobuf:"bytes,4,rep,name=issues,proto3" json:"issues,omitempty"`
	// Result data
	Result   *anypb.Any `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Metadata *anypb.Any `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Contains information about the cost of the operation.
	// For completed operations, it shows the final cost of the operation.
	// For operations in progress, it might indicate the current cost of the operation (if supported).
	CostInfo             *Ydb.CostInfo `protobuf:"bytes,7,opt,name=cost_info,json=costInfo,proto3" json:"cost_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_589bdee9fb97c360, []int{9}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Operation) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func (m *Operation) GetStatus() Ydb.StatusIds_StatusCode {
	if m != nil {
		return m.Status
	}
	return Ydb.StatusIds_STATUS_CODE_UNSPECIFIED
}

func (m *Operation) GetIssues() []*Ydb_Issue.IssueMessage {
	if m != nil {
		return m.Issues
	}
	return nil
}

func (m *Operation) GetResult() *anypb.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Operation) GetMetadata() *anypb.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Operation) GetCostInfo() *Ydb.CostInfo {
	if m != nil {
		return m.CostInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("Ydb.Operations.OperationParams_OperationMode", OperationParams_OperationMode_name, OperationParams_OperationMode_value)
	proto.RegisterType((*OperationParams)(nil), "Ydb.Operations.OperationParams")
	proto.RegisterMapType((map[string]string)(nil), "Ydb.Operations.OperationParams.LabelsEntry")
	proto.RegisterType((*GetOperationRequest)(nil), "Ydb.Operations.GetOperationRequest")
	proto.RegisterType((*GetOperationResponse)(nil), "Ydb.Operations.GetOperationResponse")
	proto.RegisterType((*CancelOperationRequest)(nil), "Ydb.Operations.CancelOperationRequest")
	proto.RegisterType((*CancelOperationResponse)(nil), "Ydb.Operations.CancelOperationResponse")
	proto.RegisterType((*ForgetOperationRequest)(nil), "Ydb.Operations.ForgetOperationRequest")
	proto.RegisterType((*ForgetOperationResponse)(nil), "Ydb.Operations.ForgetOperationResponse")
	proto.RegisterType((*ListOperationsRequest)(nil), "Ydb.Operations.ListOperationsRequest")
	proto.RegisterType((*ListOperationsResponse)(nil), "Ydb.Operations.ListOperationsResponse")
	proto.RegisterType((*Operation)(nil), "Ydb.Operations.Operation")
}

func init() { proto.RegisterFile("ydb_operation.proto", fileDescriptor_589bdee9fb97c360) }

var fileDescriptor_589bdee9fb97c360 = []byte{
	// 802 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0xc7, 0x89, 0x37, 0xc4, 0x2f, 0x6c, 0x1a, 0xa6, 0x4b, 0xd7, 0x0d, 0xa2, 0x5a, 0x45, 0x08,
	0x2d, 0x5b, 0xb0, 0xcb, 0x22, 0x04, 0x45, 0x5c, 0xb2, 0xf9, 0x83, 0x22, 0x75, 0x37, 0xd1, 0x24,
	0x3d, 0xf4, 0x64, 0x4d, 0xec, 0x49, 0x64, 0xc5, 0xf6, 0x04, 0xcf, 0xb8, 0xaa, 0x2b, 0x55, 0xe2,
	0xc8, 0x91, 0xaf, 0x00, 0x47, 0xbe, 0x14, 0xb7, 0xfd, 0x0c, 0x1c, 0x91, 0x67, 0x1c, 0xc7, 0xd9,
	0x55, 0xd3, 0xed, 0xa5, 0x97, 0x64, 0xe6, 0xcd, 0xef, 0xf7, 0xfe, 0xfc, 0xde, 0x9b, 0x31, 0xdc,
	0x4f, 0xbd, 0xb9, 0xc3, 0xd6, 0x34, 0x26, 0xc2, 0x67, 0x91, 0xb5, 0x8e, 0x99, 0x60, 0xa8, 0xf9,
	0xc2, 0x9b, 0x5b, 0xe3, 0x8d, 0x91, 0xb7, 0x1f, 0x2e, 0x19, 0x5b, 0x06, 0xd4, 0x96, 0xa7, 0xf3,
	0x64, 0x61, 0x93, 0x28, 0x55, 0xd0, 0xf6, 0xa3, 0x9b, 0x47, 0x5e, 0x52, 0x76, 0xd5, 0xfe, 0x61,
	0xe5, 0xaf, 0xfc, 0x30, 0xb6, 0xd7, 0xc9, 0x3c, 0xf0, 0x5d, 0x9b, 0xac, 0x7d, 0x05, 0xe5, 0x36,
	0x89, 0x22, 0x26, 0x54, 0x00, 0xfb, 0x25, 0x09, 0x7c, 0xaf, 0x4c, 0xfb, 0xfa, 0xad, 0xb4, 0x2c,
	0x5f, 0x97, 0x85, 0x61, 0x01, 0x7d, 0xb2, 0x17, 0xea, 0x73, 0x9e, 0x50, 0x27, 0xa4, 0x9c, 0x93,
	0x25, 0xcd, 0x19, 0xf6, 0x5e, 0x06, 0x17, 0x44, 0x24, 0xdc, 0x71, 0x99, 0x47, 0xb9, 0x22, 0x74,
	0xfe, 0xd0, 0xe1, 0x5e, 0x21, 0xc7, 0x84, 0xc4, 0x24, 0xe4, 0x68, 0x06, 0xcd, 0x42, 0x36, 0x27,
	0x64, 0x1e, 0x35, 0xb5, 0x13, 0xed, 0xb4, 0x79, 0xfe, 0xad, 0xb5, 0x2b, 0x9e, 0x75, 0x83, 0xb8,
	0xdd, 0x5f, 0x32, 0x8f, 0xe2, 0x43, 0x56, 0xde, 0xa2, 0x21, 0x7c, 0xba, 0xf5, 0x2a, 0xfc, 0x90,
	0xb2, 0x44, 0x98, 0x95, 0x13, 0xed, 0xb4, 0x71, 0xfe, 0xd0, 0x52, 0x52, 0x5b, 0x1b, 0xa9, 0xad,
	0x7e, 0x2e, 0x35, 0x6e, 0x15, 0x9c, 0x99, 0xa2, 0xa0, 0x5f, 0xe0, 0x13, 0x97, 0x44, 0x2e, 0x0d,
	0x1c, 0xb2, 0x10, 0x34, 0x36, 0xab, 0xef, 0x72, 0xd1, 0x50, 0xf0, 0x6e, 0x86, 0x46, 0xcf, 0xa1,
	0x16, 0x90, 0x39, 0x0d, 0xb8, 0xa9, 0x9f, 0x54, 0x4f, 0x1b, 0xe7, 0x8f, 0xdf, 0x55, 0xd3, 0x33,
	0x89, 0x1e, 0x44, 0x22, 0x4e, 0x2f, 0x5a, 0xff, 0x5c, 0x9f, 0x1d, 0x40, 0xd5, 0xfc, 0x5d, 0xfb,
	0xfb, 0xfa, 0x2c, 0xfb, 0xc3, 0xb9, 0x33, 0xd4, 0x85, 0x56, 0x4c, 0xd7, 0x2c, 0x16, 0x8e, 0xcb,
	0xb8, 0x70, 0xfc, 0x68, 0xc1, 0xcc, 0x03, 0x29, 0xda, 0xb1, 0x0c, 0x30, 0xa4, 0x44, 0x24, 0x31,
	0x1d, 0x06, 0x64, 0x69, 0x4d, 0x65, 0x17, 0x70, 0x53, 0x11, 0x7a, 0x8c, 0x8b, 0x51, 0xb4, 0x60,
	0xed, 0xa7, 0xd0, 0x28, 0xc5, 0x42, 0x2d, 0xa8, 0xae, 0x68, 0x2a, 0x95, 0x37, 0x70, 0xb6, 0x44,
	0x47, 0x70, 0xf0, 0x92, 0x04, 0x09, 0x95, 0xa2, 0x19, 0x58, 0x6d, 0x7e, 0xae, 0xfc, 0xa4, 0x75,
	0xfa, 0x70, 0xb8, 0x23, 0x3d, 0x7a, 0x04, 0xed, 0xf1, 0x64, 0x80, 0xbb, 0xb3, 0xd1, 0xf8, 0xca,
	0xb9, 0x1c, 0xf7, 0x07, 0xce, 0xf3, 0xab, 0xe9, 0x64, 0xd0, 0x1b, 0x0d, 0x47, 0x83, 0x7e, 0xeb,
	0x23, 0x54, 0x07, 0x7d, 0xfa, 0xe2, 0xaa, 0xd7, 0xd2, 0x90, 0x01, 0x07, 0x5d, 0xb9, 0xac, 0x74,
	0x1e, 0xc3, 0xfd, 0x5f, 0xa9, 0x28, 0x1c, 0x61, 0xfa, 0x5b, 0x42, 0xb9, 0x40, 0x47, 0x50, 0xf1,
	0x3d, 0x95, 0xc7, 0x85, 0xfe, 0xe7, 0xf5, 0x99, 0x86, 0x2b, 0xbe, 0xd7, 0x19, 0xc3, 0xd1, 0x2e,
	0x98, 0xaf, 0x59, 0xc4, 0x29, 0xfa, 0x11, 0x8c, 0xa2, 0x63, 0x92, 0x94, 0xb5, 0xe6, 0x6d, 0x12,
	0xe3, 0x2d, 0xb6, 0x63, 0xc1, 0x83, 0x9e, 0xec, 0xd3, 0x1d, 0x13, 0x78, 0x03, 0xc7, 0xb7, 0xf0,
	0x79, 0x0e, 0xdf, 0x41, 0x4d, 0x4d, 0x7a, 0x3e, 0xb7, 0x2a, 0x01, 0x25, 0xfb, 0xc8, 0xe3, 0xf9,
	0xaa, 0x97, 0xcd, 0x68, 0x0e, 0x44, 0x36, 0xd4, 0xe4, 0x75, 0xe2, 0x66, 0x45, 0x8e, 0x85, 0xea,
	0xda, 0x28, 0x33, 0xa9, 0xdf, 0x4b, 0x75, 0xcd, 0x70, 0x0e, 0xcb, 0xd2, 0x1d, 0xb2, 0x78, 0x79,
	0x67, 0xbd, 0xde, 0xc0, 0xf1, 0x2d, 0xfc, 0x07, 0x4c, 0x37, 0x84, 0xcf, 0x9e, 0xf9, 0x7c, 0x1b,
	0x9c, 0x6f, 0xb2, 0x35, 0x41, 0x5f, 0xf9, 0xd1, 0x6e, 0xbe, 0xd2, 0x82, 0x3e, 0x07, 0x63, 0x4d,
	0x96, 0xd4, 0xe1, 0xfe, 0x6b, 0x35, 0x72, 0x3a, 0xae, 0x67, 0x86, 0xa9, 0xff, 0x9a, 0xa2, 0x2f,
	0x00, 0xe4, 0xa1, 0x60, 0x2b, 0x1a, 0xc9, 0x2b, 0x68, 0x60, 0x09, 0x9f, 0x65, 0x86, 0xce, 0xbf,
	0x1a, 0x3c, 0xb8, 0x19, 0xef, 0xc3, 0x55, 0x8b, 0x9e, 0x02, 0x14, 0x83, 0xc5, 0xcd, 0xaa, 0x24,
	0xed, 0x99, 0xc2, 0x12, 0x18, 0x7d, 0x05, 0xf7, 0x22, 0xfa, 0x4a, 0x38, 0xa5, 0xea, 0x74, 0x59,
	0xdd, 0x61, 0x66, 0x9e, 0x14, 0x15, 0xfe, 0x55, 0x01, 0xa3, 0xf0, 0x80, 0x9a, 0xdb, 0x9e, 0x67,
	0xdd, 0xce, 0xae, 0x6a, 0x4c, 0x89, 0x97, 0x4a, 0xdd, 0xea, 0x58, 0x6d, 0x4a, 0xa5, 0x57, 0xdf,
	0xbf, 0x74, 0xfd, 0x6e, 0xa5, 0x7f, 0x03, 0xb5, 0x98, 0xf2, 0x24, 0x10, 0xf2, 0xf9, 0x69, 0x9c,
	0x1f, 0xdd, 0x7a, 0x17, 0xbb, 0x51, 0x8a, 0x73, 0x0c, 0x7a, 0x02, 0xf5, 0x90, 0x0a, 0xe2, 0x11,
	0x41, 0xcc, 0xda, 0x1e, 0x7c, 0x81, 0x42, 0x67, 0x60, 0x6c, 0x5f, 0xb8, 0x8f, 0x25, 0xe5, 0x50,
	0xe6, 0xb4, 0x79, 0xc7, 0x70, 0xdd, 0xcd, 0x57, 0x17, 0x5f, 0x42, 0xd3, 0x65, 0xa1, 0x95, 0x92,
	0xc8, 0xa3, 0xaf, 0xac, 0xd4, 0x9b, 0x5f, 0x94, 0x3e, 0x35, 0xf2, 0xab, 0xf4, 0x9f, 0xa6, 0xcd,
	0x6b, 0x32, 0xd2, 0xf7, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x74, 0xd8, 0xc1, 0x38, 0xaf, 0x07,
	0x00, 0x00,
}
